LOGO_TEAMCELL_PERSONALIZADO_B64 = """
iVBORw0KGgoAAAANSUhEUgAAAZkAAADpCAYAAAD28Eq7AAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nO2dCXRVRZ7/HxjtsMR0ICz/EZooUY6n7QbabuLCjoBN2ASaZgkOTKJnhAYEDY5CK/SA04CADWOcaaFxZElEUITEAVqWJKgsKkHP6Z5I2BeTEBNCQoJC8/7n+zrXvj7ztntv1a173/dzTh2W9969VXXr1rfqV1W/XxOv19vX4/Hs9RBCCCHWsqApK5QQQogoKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBEGRYYQQogwKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBEGRYYQQogwKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBEGRYYQQogwKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBEGRYYQQogwKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBFGDKuWGKW2ttZz/PjxoL/u3Lmzp2XLlqxjC0Gdo+412rdv72nXrp07CqfDv5xoR2hPdnP06FHb82AWme8lRYaERVlZmefjw4frP/7448qPDnx0fefOXZ2M1lxSUqeq4cOG1w4aNCixT9++zShCwUFHm79vX31OTk7F+g0bOgb6ctrEiWfHjRuXmDp0aDNFsh4RKOfWre9U/fGPf/xbYeH+xEC/TU0dcn7cuHHNR458JEFG24HYZb3yStlrq1+7taam1pF12xh4Dx/LeOxv6RkZiUIHKV6vt6+XED9KS0u9udu3182YPv1MUlKnSjQVUSklpUfp/BdeOLe/sNBbU1PDR6EjK+uVS3FxLesiqXt8P3vjxnplChEGRsuJ34nKE9ri7FmzSkW2fVWSwHqcT5Eh34KXCo1NtKiESr169bwIgYtmwYHI9+vX9ysz9Th61KiLqtch8me2nPg96stKSkpKfO0wGgRGcHsxLjJFRUVeGaNcN6TU1CHn0Gla/fSsAi+oqiM25MvqDkR10MFFOqoPlJKTO1/C9VTEynLiOlaVEx0t6i0a+6qM9PSLFjeVyEUGDwCKF40PwGxSzYyhDRScUHcyxAZtGya7ZcteOqVP69a9USlL6ER0cLieajMalcsZ7f2bxaazyEQGI4VoVXgrExqxnaNz3NupL5IIsQl3Jpc2ceIZCLNIRD0XmJRUEpqxv/pVlYhymh2J4/m6pZ8xmlq0aH7FwncsfJGxcmrLZO30PlzQySxauNAVozSMtqzoNAvy869E2q6nTJ78pYgOG3kRWWdzMjO/sjzTBhBdTlzfaN5GjhgRFQv94bxfFj3u8EQGL1S0LYLJSPHxt9bLGl3ixcP93FR/mFWbmVlgnczovVGXVg8SZFgJMMiwNNMKlhPXN5IvjN7d9H6YSVhrt+hxhycybhn9qphgprHoYTYKRAwmBDfXIdpnpGINgTB7X8yArDIryDTT2LkJRVY5jQwAsB7n5vck0mRR2w4tMlR3xzzM7xFNa2iYaUfSsVhVL1jrsOJZ4ZyQzPoyY1Iyg6yNJkZmbNjkEQ3vSrjJovXH+SF9l/35z7uqxB0FJaLquLCgoK579271JSXH46OhknFCHOVFuUN9Ny8317J62bt3X6uc7OyrZq8DLwpW5CdcUoemNgnlEkgEBw8dvEXGfQoKC65ILxxpnFAzGZzxiHZFF51Qx1YMGTTMrDW4IYUyB2Hh3spywmxmdm3Njnq30tynWjlRtkjzxpnMd5O0mUxBQUEr6rNYrKxjjNKHDhvmGv9KRkD5X1y0qCLQT/fu2/sDK+8Hf1bwuSWiLCJBvsePH1epd0LpFtzkY8wu4HjVCkKKDB+WeKyqYwrMP5g7b17iM3PmVDb22alTpxOsvt/OHTsd2VPD3Dd8+DBXCg0xDpxnWuU0k/FkXAIF5vssWbq01auvZlXLuNe7294N6DVYdSA0//673zUqyCQ6gXdmqwoeUmTi4lrWs52JxWwdU2ACM3XqtHjUj+j7OH3GD0EONPMj0Qfc/1tV6JAiM2L4iIC2bWINZuqYAhMa1I+MQFOIueNkIDRW7JQjzmbRwoUVVsaXCSkyCILENiMWo3WMjpMCEx69evWsF71lt7S0VOj1ZTB+woRYGTM/oib9+vWtfG7uXEv7/JAig8iFNJmJA3WLOo70Blio7dOnN0edYQJz1sMPD67mAndoMHCx4wwNsRcIzLZt2y3fTRxSZBDedPHixd/w+YsBdWskhOzkf/7niurqy7HOKKUa4ABm9+7dhG0EcFMYaRxspdBEDzCR7dmzt5WQNhyuF2Y6yLQ+GY1/QV9yaiYzqFgmEQ5cZeY/UqLtMCYOrEqI0zQ/JlwxWrv2dZ/bDp6bsQaYyXbs2Bkf6cgBblNwBkTdkhG3gJkyztDAhOKmWZoKpKT0KHvu2ediWrdu3frgoYOnZWYppUdKp5ZxcZ6uXbuiLxffnzNomfxkNCY5RpVuc9fvpmQGlesBgdRMFU6HzHxHisyZDO5lVZ0qTmi3Mno6d+7sOXKkKB72O+Hq51K0xTUjWwRfeP75Mq7DENlsefvtgN4TCAlF2OYyDUybscUtPSPD5z04Lzev6sDBAwkiXHW4DU1gjJgesAi7fMUK6zavW8wdd9zu6d+v//cuunrNGlWzTCIAZ2ji4+MrrN7eSqKASMxlTsaKIFVmktkY6yqFhb3jjtu9r2ZlVW7ZvPnUmTNnztXW1gaNonft2rU6fC8nJ7t0zOjRSpRBRDKDU8poNuCZys+D5jIhhB/j38nYHT46ISHhqhmBkRk1MVgaMKC/94P9+01vRYEo5eXmXsT1VCiXVckMTiqnGaFR+XlQZIQQ2ZqME8HhO+yQQVArO7KPXWSHDx/+gZndOS8tXXrW0kxFyIAB/T0f7N9f9v77uz0PPPigaZNdixYtEoakpibu2LGzbv36dVIcWBLr+PW4X3t5hoaEi6tFRhMYeJm14/4QmCNHipphw4RR4A9r/YYNHe3IP9ZZ8nJzK6wSF39iYmKaT5yYFl9TU1P94qJF9CrhEK5cqWvOw5okXFwrMm4QGLBk8WJbvC6OGT3ac+DAwQrMOETfq2XLlvHPPvdcs7KyskoIG1EfnJebMmVyBd30kFC4UmQwwhoy5JcVThcYvMB27CiDwGTn5NS3adNGqomxbdu2rY4e/awa9yfqAxM0A56RULhOZCAwmMrbuQZjhcCA/H37pJuQYLZ6a/NmmLJs8eyAWQ0EjkLjDDCQm/Xkkzw3RwLiKpHRBMYu1zdWCgzIycmR+vLOycysg9lK5j0bAwJHoXEOq9es4WHNCDl/7nzUHKpugi3MGJAokBdTuE1gYIKIi4uz5FrhoJnI7JrBNEZtbW11164/jT9x4qQqWQrK33foGqNJkyZqFioCsrJeqX7iianxwX4hs5yRPo/ly5edfuqppzsJy5Af8F/2wx/+0LJwHV3u6tJ00KBBiQgdopCvuQWuOCeDg5bwKGrXuQHcG3mwkv2FhdLyj8OVNTU1l+x+jo2Bczl2PVfR5zL0OKWMoVKoMzQqPw+3eGFGf5SV9YohD+8CcP45GbtnMMDKGYzGpk2bpJ2NWbVyVQXWQmTdLxKwdTojPV3FrJFGQMAzeApn3dgH+sKpU6f5YiepsM3c0SKjgsDkbt9eb7XAgLWvr5WycQEduIxtymZ48T/+gwvLDiJ1aGoTnqGxn4YgfbafZ3KsyCAOeXJyssdugUkdOtTy+6NRyCrX3HnzbDmHEwnYSs3Dms4BbZeHNdVAexY41G0XjhQZCAym5XbmQZTAgP/761+ldKiYxSQlJSnr2VnP9BkzGALcQfCwpjrgWUybOtU2a4DjRMbtAgN27dolpUHMfuopW32iRQLWjDibcRY8rKkOiAl09OhRW+7tKJGJBoEBxV8U3xB5fU+DX7K7777bFp9oRhk/YcJlJ+WX8LCmSvxpzRpbBpWOEZloERiwc+cu4Xv1M9IzHDcrgGkPHqGJs+BhTTWQtZnIH0eITDQJjCz6DxjgyNHlmNFjqhTIBokQRNbMyc627OAhiRyszdixAUB5kYk2gZFlN01OTr5Fyo0spk/fvjTwO5TxEyZEjSsVVSktLZWeM6VFBiMfzmDE0Lp1a0fsKvPnRz/6kTL+MgghoVFWZGDDtXvk41aBcfK6BqJqKpANQhyJHT7NlBQZCAxsuHbmwS6B+fzzz4SvOdyexMBghEQbcOIrwjtJKJQTmWgWGFBeXs5tuoQQyxkxfIQtm32UEploFxhCCBHF05mZtpyLU0JkcCL4sYyMCgqMLyZEWzvvT9wP2jkfc3QxcsSIsq5du9pSZttFBgID1xM4sGVnPlSZwXTo2JGzKCIUtHMKTfTQokXzupeWLbNtN6mtIqMJDFxP2JmPOZmZlaqYyGTs/tizd4/wexC1QXtHu+djcj9v5rzZxI4Ffw1bRQY+jVQQmMVLltiaBz0yGoNTwhk3xldffaV8aAKngHZPoXEv2E1WkJ9fZ/cA2jaRwUl+u01k/fr1VUpgZHLhwoXTTsx3SUkJXf5byG+ff74V3gPXFIj4mD1rVtmxYyXNevXu3dzuGrFNZJ6c9aStnQVerG3btkelwICzZ886MpbQnt27lY7i6TRgnsV7QKFxNklJnapSU4ecX7fujSq4jlm2fHm7du3UcOphS0eDiHkIDWrHvT06gbHj9Gs4DB48SPgs461Nmxzl5l9j957d3BhhMXgPsrNzWsG84qqCKcyUyZNLvV6vx6p08uSphNzcvNvS0iYlqCIuGraIzEcffWibJ13VBQbExMTEiL7HsuXLPVeuXHGUR+NTp06V7d7NTQsiQMd05EhRMwqNHO75yT1fR0M5PXaJjF2n2p0gMKB///7XZdwnf9++v8m4j1Vkb9x4q5Py6zSw6aSwcD9nisRSbBGZPXv2CB+p++MUgQEpPVKEBy0Dy1csd8z6Rm1tbfVzc+eyAxQMDuzxDA2xEkcu/kaKkwQGJN95p5T7wPQEE5SUm5lk1cqVjox/40Sw5TV740YGGCOWYIvIyDIHeRwoMJ4G+3hKSg8pnX/m008rH1fm4sWLFZzFyGXc+PGxPENDrMAWkbk55mYpcWKcKDAaw4cNv0nGfTZv2eJ5Ly9P6VDMzz37LLct2wDOkGWkpzsyTDdRB1tEZkhqqvDRs5MFBvx63DhpHev0GdMTy8vLlRy1btiwvnr1mjUK5CQ6WfHyy4k8Q0PMYIvIYBcLDg+Jur7TBcbTUEeytpPCzcz999/X6tq1a0rZ4U+cOFGRljbJtvNU5B+HNXv16skZDTGEbQv/c+bMEXJvNwiMxpTJU6S92BCaCePHx16/fl2JnUWYWQ0c+BDNZAqAd2nt2tcTeYaGGME2kZk06dF4qxutmwQGjB07VuqpfKzPjB83rpndQgOBwczKyY483QZm1jysSYxgm8j4XFlszLbsepjOu0lgwIM9e0q/J4Tm4YcHN7NrjQYmMgqMmkBo8nLzvNFeDyQybD0nY1VMi4SEhK8xnXeTwGikTZx4VvY9cX4GHX1hQYFUocEif+fOnRMpMOoCr748rEkiwfbDmNgmuWjhQsNrD9hieebMmR/YGZRHJPMXLLDFkSU6+t59+rR6Zs6cOpy2F3mvo0ePVjz00AAPF/mdAQaHWVmvCG0TxEV4vd6+XgUoKiryJid3voQshZNGjhhRit9EA7NnzSoNt15EpDvuuN27fv26S9euXauzsrpPnjxZmpGeblu5rE5mcEo+9czJzPzKTc9j2bKXTsnK25TJk7+07EGozXxlREZjf2Ghd8b06WcGDx50KimpU6X+weDf+CxaxEWjpqbGGxfXss7ulxZi8+KiRXXl5eUXzZTnzJkz5+ZkZl5RuYOS0anpcUo+/Rk9atRFtzwPmSKjQkKfgn520cKFF0tKSixtFzrUExnSOFlZr4Q9y5ORBgzo7301K6sSghFshlNbW+v7zpbNm089NXu2q19aMzgln/5gANSvX18lZzSREm0i458EWYfmN4HIeDyevTSBqk1tba2nQ4fbrlZXX5bikscIAwb099yedLvvl5cuXfLtVIsm/q4VxmjSpIm0mjKTz8ZA2+zevVu1nYEIGyPSci5fvuz0U089LcUDusrAOSp811mUxQXSXe4TY2Dn3Ib1G7xDhw1TtgYZUCw6QdvcsWNnfPfu3epramrpyNThjJ8wIRZHCZ6bO9eSw9BR4erfLWBXD917EBXRDmvy4biDufPmJRYWFNRZURiKjMNYteo/6WqFKAmEhmdo3MOw4cOawhRqFoqMw0DkQjPniggRCWbbFBp3gPXfdeveMH0eiiLjQGbMnJlIs5kx6LZePFZ58iD2s2TJkhtmM0GRcSCaV9wWLZpbYjONFjQHqtFeDzKAJw8KjfM5dep0QlmZuSC9FBmHAvv3mzlvytv36nDgPTg7O8dVDlRVB0LDmaPzKS0tNVUGpUTm6NGj30lWLDq5GZglsKc92ushFBAY7Hxq1054QFbDiAzip0e2q37MHO0QGoYksI6C/HxTUxlbRQbTsKdmzy7r0KHDVziM1q1bt++kuLg4z6S0tLN5ublsMAHAoSmaJQKjCYzqDlR//OMfSzF9jhg+QupanhZZMz7+VqmDod69e/OdsIiEVgm3mLqSHW5l4IoiUqePvXr1FOlfx/Go7qzQjgTfTI21GVF5McO6dW9Uyqgj3MeOto7nINP/npFyynoGTksmXc3I912GxhYff2u90YqGMzeIFPk+FJp/pEAC41VUZEpLS6XUiZ3vDp5HixbNpThGRX0ayV+0vB+i61KHXJH54osvamJjY2vNFhoO+Sg0jZO7fbvt3prtTsEExquoyAC4fxdZd3CyajqTJpHRPuEZ2mgub7vttopof3/0CRYkk49cnshADa2cLptpSG4nmoUGMYlCmVVFmW3MInI2g3pRZWAmun2aGXmr5u3c7mSBeVWeyIiIO5G9cWO9jLw7Edk2cBVSuDNcxNAQkV8rENUBqxaDSVQ5zfYJaD9mzPluShYNTOSIDBq4iMpHJyo6704GIzqVg0pZmbAeFe4LgXU9q++fmjrknFVNxeq1NXToKjZjq4UG9WZFvgry810XUM9IsmhgIkdkEM1SVEWo+gKpBEZ3shZcZSeUK9LRq4gFXqvboVUdsOrvB/JnRdu0er0p2tc2LWw3ckRGZGVAwETn3w24cVaD8hi1vyMKoFX5ELXegZEkrm0kT07a8o98Ir9G616UKdAqAXRSgqkQMzkLq1G8yIgylWkJcf9F5t9tuGFWg47F7EjLyu20otc7UNZwxcaKurELFcuJQUykZ/qcmLD0gHIKGCyJD7+8auXKshkzZwr151FSUuJR/US3SsDTwpLFi8uWr1ihrp+VRkhO7lz98oqXb4E7HSuuB08SQ4cNM3UtuLW3Kj+hOH78uOe9vLyynbt2Xgfa17vc1aXpL3r8ouX99z+Q4Ib3AOV8MyenoqCwAIMAz4EDB9rdd999ZTExMTGDBw2OGZKa2k52OfHO/PnPu6oOHzpcW/xFsWnPxKpw/333x/z85z9v1adv32aC/PotED6TWbbsJSE7efTJrlPMTkcbpam+C03kqBWmASO7iVBnFpsVCHEj813hhTknJ4cu7w0Ah5HLli9vd+HCl83WrXujCjMFlfKH/GCmcOxYSbyo2UKv3r2bnzt3Pnb2rFlhOwHEd48dK2mG34rIEyFuQri5bP36dVWTJj2aILrOampqPHTjbh6YkHJycirWb9jQ0Y77w6HllMlTKsaOHdvxwZ49pd4bXr/z9+2rL/6iuHzPnj0xmkkKZpr+/ftfT+mR0qlrt25sZ4SEzwLhIgOX/fCoLBqZtvFoAc8uLze34sOPPvy6oKCgVU1NreX1Cxf3PR/sWTv44cGuWVMghHyLeJEBcOMvmrSJE8+uW7/eltF3tIDFz48PH67ftWtXxcFDB285ePBQRBsHMEuBC3ZtVpB8550elWO8EEJMI0dk7rsvpSzSDskIiODGTks+2A0UKsBc165d3Vl4QkgwFsTIqJ5fPvzL6wcPHhJ+H2wxTEubJHz9h3wXmrgIIYGQsrvsoYceuk3GfRYsWOCK3XKEEOIWpHTKsL3LoKTkeDwWqwkhhKiBFJHBOklKSo+wzyGY4U9r1pyVcR9CiMfzwf79IdfjSHQjzbyEdRkZ91m5alVH7IIihIgF71nPXr08o0Y9otQh3mjjxUWLKh7LyKhQVeyliYysdRmwZvXqCln3IiRagYUC59Nmzph5CxuBfcDH2+o1axKxy1NFpOwuAzi9jXMSIg70+fP7xb9vMWPmTJ7MJo3i72jSaseL8Jqw6j9XlQf7DpxaDho0KPHnv/hFMydvu4+WA9BoM5vfeqvmmX/7tzgFsuMsZIVfBjJdZlsdxIg4n3BcySN0BCJnmnF5HmlbTZs48YxTYr9EK5oTVdXCWHt14cRVzJt0B5lTp02TNmTLzMy8mWszxNPgkww2a7j1xw7EYJVy6tTphLnz5iX+0z/9v3rMSMxUIFzynD9//rR/OnDgwNmcnOyyjPR03/fgJy45OdmTk519lQ9MTaqrL8dGex0YRuZMBhiNgGckYeYks2xEPRDOwEybMxI3XvttONTU1Fx6cdGiOqP3w+wMMyHMwLRrYGSL2VgksyPM3BAyQ38t7TrBoo/uLyz0RjLrQ35TU4ec09cx/o17+98H1/3v//6vq43ldeUf/lCqL59/PSAUg3ZdKwJxaXm1craAfGn5TknpUarlO1C9o7yNhZcINJPBv+e/8MI5fK4l1AnqzmhEWQPICb+sR3bsbJohohc8eyti5eCFj6QSIxEZjYL8/K+034UTOwedTThRJBFmOtQ7gM+DxdRBBNHG8oSOCp/369c3pDCGG0oaZm5NFKZMnvxlY/WhRdtF5xzOda0IKWy1yCBCbThtMyM9/VvTrSbO/s/TX2TwZzgDKzPhyyNAvsigwmQGycJLJrN8RA3QzozGx28sRdK5GBEZr05o8H4EG31D9LR7PDV7tvcvf/nLGf3ntbW1lQcOHDiTkZ7+bV4CCRfuoxeYGdOnn8HsBOXFb/SdVWMj5XDKqh9YYtZ25syZc/rPr127VvfB/v2lAwb0930Hzw0dqdZ5IvBhY/f1D5+tzzv+xL/1n5sRGqtEBvUN4dDXR3l5+XcGMXh+ebm5F7X6wPPR14d/HvT/71/X/tf2r2u0NcEDcfki45W8AcBs4yLORN8RW5HQ8YVbEUZFBmjCEGjjCsxp+PyOO25HpxJyhgXhwncDCQ3MSVqHHaiz0e6JkbT+/8MRGe366NT8O7zGQOeqdX6a6SuQyGgJM6lAI3K9uRSdtVHTmVUig9kDrjNm9GifqTTYd69du3ZFM6WiPrRBUyCRef63v/1au3Y4db1q1cp6CUJjj8igQDJFxkzjIs7DvxOyKoXbwZgRmZMnT/oGYOhg/T/DYEkTmLKysrDXbvBdTUj8O2PNBAPbfbBrYGDov14USmS0/EJgMIION79602EokYGAhHq38bk264nU9Klhhchg4KCJQCT1oV+zCyYyRupaE3UImKA+0h6R8UreAGCmcRHnYaWZTJ9CdcQaZkQGaKYM/9GlVi50DJFec/36db7f+m+GCWSSCodgIqM3wx0/fjzi/Oo71mAiE26nr3XwjYl3OJgVGf0yQTizDH/0ps9gIhPJ4EMj1OzZJPaJjOwNAGZHIcQZaJ2JiISXOZxKMCsyWgcLU5P2f1hj0EaqRsEMCB2d/ufauoWR2X4wkdHeb3RgRoApKZTIRCIY2iYFo8/FbB+imQ3xbI38XpvhBhMZo9fW6tq/bViE3HMyevr07dsMHgBk3nPMmNHVdObnXnAuaurUaUHPwZihuLj4VhmV16VLF5+3gPLy8sva/23atMnn+HX2rNmGXSZlPp1ZBY8bek/lM2bO9EWTxTmQDh1uu7p+/boqK96RnJwcXz4zHnvMkMPali1bxmvniALRpUuXy0G/oEPvVcEO9ys5OTkQXdTHFSO/T0pKajdm9Oig3xn5yCOG2gbqGtf2bxtWYZvIwOXL4sWLv5F5TxzEm/Xkk/Rr5lKmTZ0q9NnioKZdNVf8RfEN/BkTE/P1hQsXTkeazp49e76oqMjnY+zzzz+r0q4LNzoF+fl18fG3XoXQTJr0aEJcXJxnUlraWTOHUd/d9m4i/rznnnsM+3a69957q8L4WsTYMdDMy3vP57uxTZs2iUavMWDAgKD1cffddxsOPz/mV2N8J9f1bcMqpPkua4xJkx6Nf+aZZ6T4M9OAI7mRI0fWR4vPpWjh1Vezqre8/bbhFzgckpI64QUULjTl5eUBZ0yDH37YckezvXr3bn7u3HnPunVvVC9ZsuQGxBReCNZv2ODzN4jBIN7VSHwBau90ixYtDNdX27ZtL8uob6cgsj5ujrnZ522iYfZs6T1sFRltNjN16jSpHf7f3YuUMGywS8AUX6SZTKPngz1rZXR6u3fv9t2jy11d2jb2+fwXXjgfd2vc9arKqr8d/vjwTV1/2rWuXft2zUNd9/y587GtW7e+KS1t0vfEGO/iE09MjX/iiam++kRcJoTNgFjg/Xz22WevfvLJp7F8Z0ik2CoynobZzNy5876uqqr6gcz73nvvz66eO3c+lp6anQ3s67169YRZR/hAZdy4cUJnSuDKlStVm7ds8YkMPDRr/w9P0fhz9KhRFS/Mny80bEbXrl09f1i5suOiF1/0bN36TtVvfvObZjClRfLOIEjhwYOH2sFM17FjR0P5DTajcxqaB/rr16/Xx8TEGGqrH374Yadgn5u5dnFxsW9Ak9IjJeg9jGB7THw02HVvvHFD9n3x0gwfPqySGwGcC57dlCmTK2SYW9FJYLOK6PusXfsn3z1GjhhRpl+sHjdunG+m8smnn9wkOg8aeDfT0iYlQFiSkztX42zCB/UAAAvrSURBVJ2B6ITz25QeKb711rzc3JAzrEBs3rLZJ7YdO3a0vOOTzYjhI3zrhZ988omhdUMIyDtb3wn6HaPX9viWEVb72p2IUPm2i4ynISYFXirZ9927d1+rf//d7ypl35dYAwYJhYX7hc8uAMy6ome95eXlldOnz/B5+52/YMF3PJYPHDjI1+FivcSsd+hI+bsp7Qlsc/12l1Qo/iU93bcIvfSlpQnoICO954kTJyp2797j+/tdd3WRWVwhaLPg1a+9ZmhxftfOnVdOnDgZ9DsvLV1q6NoffvBBGa7tP7CxCiVEBry0bJktkZuWLF3a6pk5cyg0DgPPDIMEGbnGziuYdUXeAwJz//33+cqzaOHCCpis9ODlnz1rlm8gNjFtYhOrZuBP/Ou/Vq9auTLsAR6CvIXzPeQ/Iz29Ap3X0iVLIsoTROnxxx+TMniQBQbSvXr1rFi9Zg0C5kU046itra2ePmN6yPrYvGVLxNe+du3a1UmPTvL1vf4DG8uw6zBmY1jtbyqSFI7nW6IGstsJPOZGUvBID/3BYaHmXyyYq3/9Kfpg/rr0wLVLMNfuWl6D+a7SOxvVe84I5VYGv0M+I/FS8M0339TD7UqwQ9TafcM9HKth5kCl9lscijUK6lhzbwPXOeFcJpz60J/4j+TacD+jXdtISIswse/Ef2P4e4Sl0BB/ZHuKMOLFW/ttMBcfFRUVpeh49R1IOC+6PnwBOiy9a3w9EBW9t99AaM5qcc3G2r/ebby/77NwHGTqhWZOZuaVYE4h9WKLvGsxVlQSGdST5uk5VGoMffv9n/95/WowP2P+g49QIrNp05vftg04vwx2bbj60dwX4fkE8vaA523Sp5laIuPVOdWzK0U6aiXysMMVkRHvtJHeAx1DJO0OefL3/YeOBi5i9AGwtIQOO9C19CLgaXDVAqeZEFf/6wSK6xJMZBq7B8ITbNm8+RRCFOzcsePcq1lZlVqHByHT6iJYMC67RCaSFGjQgD5OG0xDROAOBvWhJX19eHQ+xTQBCebqH6LQWF1rKScnu9R/YBNMYHDPYCIUBuqJjFfnDtuuJHDqSAxih8AYdRgYTl7x8kIQ8F2jLzB+G8wZKIQinDAXuH8wE2SgwGeaeIT7vqA+A8WSwv9jVqWfKQUSenwnISHhqt63W7j3Dya4wcD9rBIZr67Og8XWQvvwj/45cOBD32uT+H/kT9+OQrUNLeBbMCJ9vgGY3wQig41WshbAwgE+qNq3b29rHuZkZlYuXrJEysIyCQ4WpmfMnCl1YwgWad97738TnXCOCmeF/u+vf60v/qLY5/MMZx2wFTXSnULYTHC0qMhz8NDB056Gw6A4qxPsOvhNpHX0wf79nk8//bTs2vVrV7X8du3W7TvXwXd69url2zp++XLN97aOG7mvmd+JRP/8bo65ObZ3nz7tcOi1sXxGmn/0paWlpXAdVJbQKuGWn/zkpwmBrt0Y2gYTE3W2QMmZjNfmTQBawoyKcWjsRW+LlpkYttteMHvyNBKagDgONc1lXgHhc40mk/ZIYuL5623LMpOguBokTPQDCwkx6IlY7HP1HwpMzzZv3iLcH1UocBaDngHkAvNB9+7dqmWdg9EDty3w4aVGTbgLPNedO3YELBN8pj0ycmQZzq7h31lZr1SLOBxI5KLkmoyeFxctqpg7b57tB7NwIC8/vyDW/5AcsZac7Oyr4ydMiLWjWmH/P3asJOgaBDEGBKRbt27f1vOUyVMqOiV1+tad1NatW1vovTfgQOpzc+e66kBmlKLumowGzCayQzUHSzSliAHP2a71Fy2FsxOLGEc7kxMs4V1nBFtXoebuMn+wQ+LOO5Olxp0JBnYerV37eiLdnlsDzChwdCnLD1ljcOQsB7zLHx8+7NtJdeTTI02rLlU17d+///W2bdveev/9DyTwnXIdCxwhMqCwoKCud58+hj26igA240iDOZHvAvNYxmMZN65cqbPt2fbr17dyz5693K5OiPUsUHbh3x9E70OnrlKeECgLC9Qi4mK7HdRZ7969KrD+YqfAYH0gOzuHAkOIIBwjMgC7fnBIUoGsfEtJyfF4LGhigwJ3oIUG5pKnZs8uQ53ZaR7TyMvN83KhnxBxOEpkwG+ff74VzBsKZOU7YAdchw63XZUd68NJIA5/58531C1fsUKJXh0zY8yQFcgKIa7FcSKD9Y9t27a3wpZiBbLzHRA5cOiwYc2w158mtH+AurjzzuRqmBftNI3pwYyY52EIEY/jRMbTIDSffPJpLOzpCmTne2x99912MAdhzSGaZzbwPwXBRV3ArKhAlnxgJky/dITIwZEiA7DV8ciRomaqCg3AmgNmNrffnlQFU1E0rNlgzQVlRZnh4BCCq0C2vgUCg5mwItkhxPU4ZgtzIBpckChzhiYUCKE7ddq0dm47DwCT2J/WrDm7ctUqQ3HGZaAJDLecEyIN55yTCYbThMbTcKDz8ccfv2ngwEEJTt7dBHPg6tWrL6s2Y/FnyuTJpStXrWpPgSFEKu4QGY9DhUYjJaVH2fBhw29KHTo0UXXfaNqJ7V27dlWsfX1tohPqm7GBCLEN94iMx88Jn1PRnAeOHTu244M9e9peCoj3Rx99WHX40OHabdu3tTx16nSCk6qWAkOIrbhLZDwN7mdSh6Y2ceKMxh8ITu/evSvh20mLmAdzj6j1HGxMgKh8/vlnVTt37Kx9d9u7jpipBIICQ4jtuE9kPA43nYULBOiBBx4ob5PYpmn3n3X3uUxHuNwOHTsGLTMEpLy8/DL+fvrU6abFXxTfuHTpUuzBg4dcdeydAkOIErhTZDwNQnPvvT+7igOSCmSHSIQelQlRBuc4yIwUmJTOnTsfq6ILGiKO3O3b6ykwhKiDa0XG0+AZAC7cVfPeTKwH5sOioiJP6tChrjWREuJEXC0yGvBRVZCfX6eydwBiHJw5gvcHhsYmRD2iQmQ8DfFo0BGhQ1IgO8QiRo8aVfHee//LKKWEKErUiIynYZ0GHVJGejqFxgXADLp5y5ZEnuInRF2iSmQ8Des0r61enZi9cePVFi2a1ymQJRIhycmdq7H+Qlf9hKhP1ImMxrjx42OPHz/RHOYWNXJEwgGzlyNHiuK5/kKIM4hakQFwTAlzC2Y13BSgNlhLKykp8c1eaB4jxDlEtchoYFZz4cKXzbhWoyaYvRQUFHJxnxAHQpFpQFurwVZn2PyVyFSUM3LEiDJt9hLtdUGIU6HI+NGw1TmeBzjtAyKPk/vvbN3quuBuhEQbFJlGwKwGo+fS0lIPTWjywLqYtrDPk/uEuAOKTBCwMQAmNGyXhelG2Yy6ADi1xLoYF/YJcRcUmTDAdlmYbmDC4XqNtcyeNasMM0Y4taS4EOI+KDIRABPOsWMl8fsLCzmzMYFmFoO4LFu+vB1mjIQQd+LaeDIyQLz7t9/eUr1kyZIbTgtLbAeYBb684uVbuN5CSNTg3ngyMsAIHGsIJ0+eSuDsJjBpEyeeRf1gFkiBISS64EzGYjC7WbN6dcXvF/++hZvDP4ciKalT1Zw5c5qOGjU6nuYwQqIW94ZfVoGjR496CvLzy97a/NZNhYX7XR+tEcIyfNjw2n9JT+9I32KEEIqMRLQZzmurX7vJLes3WMAfMXxExeCHB7ccOHBQAmcshBA/KDJ2AMEpOXbMc/DQwdN79uyJyct77zan5D0lpUfZ8GHDb0odOjSRsxVCSAgoMipQW1vrOVpU5Hn//ffPf3Tgo+s7d+7qZHe2ICaJiYnX+/fvf73LXV3adujYkeGNCSGRQpFRFcx2cI7k888/qyovL7985NMjTS9WXLxRXFx8qxXmNpi6HnjggfI2iW2adv9Z9xuakLRv395DsxchxCIoMk7m+PHjvlmQhiZI/kVK6ZHSqWVcnO/vcDjJk/WEEElQZAghhAiDhzEJIYSIgyJDCCFEGBQZQgghwqDIEEIIEQZFhhBCiDAoMoQQQoRBkSGEECIMigwhhBBhUGQIIYQIgyJDCCFEGBQZQgghwqDIEEIIEQZFhhBCiDAoMoQQQoRBkSGEECIMigwhhBBhUGQIIYQIgyJDCCFEGBQZQgghYvB4PP8flGWdVA27QnQAAAAASUVORK5CYII=
"""

# Frases motivacionales para el footer de órdenes "PARA REPUESTOS"
MOTIVATIONAL_PHRASES = [
    # --- Frases normales ---
    "Cada día es una nueva oportunidad para empezar de nuevo.",
    "Lo mejor está por venir, sigue adelante.",
    "Tu actitud determina tu altura.",
    "Los sueños grandes empiezan con pequeños pasos.",
    "Hoy es un buen día para sonreír.",
    "Nunca es tarde para ser quien quieres ser.",
    "Haz lo que amas y el éxito te seguirá.",
    "La constancia vence al talento.",
    "Cree en ti, tú puedes con todo.",
    "Sonríe, la vida es bella.",
    "Todo esfuerzo tiene su recompensa.",
    "Rodéate de quienes te hagan sentir en casa.",
    "Un pequeño paso hoy es un gran avance mañana.",
    "La felicidad también se construye con detalles.",
    "Agradece lo que tienes y sigue creciendo.",
    "El éxito es la suma de pequeños esfuerzos diarios.",
    "No cuentes los días, haz que los días cuenten.",
    "La única forma de hacer un gran trabajo es amar lo que haces.",
    "Cree que puedes y ya estás a medio camino.",
    "El futuro pertenece a quienes creen en sus sueños.",
    "No te detengas cuando estés cansado, detente cuando hayas terminado.",
    "Cada logro empieza con la decisión de intentarlo.",
    "La disciplina es el puente entre metas y logros.",
    "Haz de cada día tu obra maestra.",
    "Lo que no te desafía, no te cambia.",
    "El optimismo es la fe que lleva al logro.",
    "Nunca subestimes el poder de un nuevo comienzo.",
    "La perseverancia es fallar 19 veces y triunfar la vigésima.",
    "Tu única limitación es la que te pones a ti mismo.",
    "Los grandes logros requieren tiempo y paciencia.",
    "Hoy es el día perfecto para empezar a brillar.",
    "El trabajo duro supera al talento cuando el talento no trabaja duro.",
    "Sé el cambio que quieres ver en el mundo.",
    "La vida es 10% lo que te pasa y 90% cómo reaccionas.",
    "No esperes el momento perfecto, toma el momento y hazlo perfecto.",
    "Cada caída es una lección disfrazada de oportunidad.",
    "La pasión es energía. Enfócate en lo que te emociona.",
    "El éxito no es final, el fracaso no es fatal: el coraje de continuar es lo que cuenta.",
    "Hazlo con el corazón o no lo hagas.",
    "Las oportunidades no ocurren, las creas.",
    "Nunca dejes que el miedo decida tu futuro.",
    "La mejor manera de predecir el futuro es crearlo.",
    "Pequeños progresos diarios llevan a grandes resultados.",
    "Tu potencial es ilimitado, solo tienes que creerlo.",
    "El esfuerzo de hoy es el éxito de mañana.",
    "Sonríe más, preocúpate menos.",
    "La vida recompensa a quienes se atreven a soñar en grande.",
    "No busques la felicidad, créala.",
    "Cada día trae nuevas fuerzas y nuevos pensamientos.",
    "La gratitud convierte lo que tienes en suficiente.",
    "Sé valiente, sé fuerte, sé tú mismo.",
    "Los límites solo existen en tu mente.",
    "Empieza donde estás, usa lo que tienes, haz lo que puedas.",
    "La motivación te pone en marcha, el hábito te mantiene en movimiento.",
    "No mires atrás, no vas en esa dirección.",
    "El único fracaso real es no intentarlo.",
    "Tu actitud puede convertir un día ordinario en extraordinario.",
    "Cree en el proceso, confía en el viaje.",
    "Las estrellas no brillan sin oscuridad.",
    "Hoy decide ser mejor que ayer.",
    "La excelencia no es un acto, es un hábito.",
    "Nunca es demasiado tarde para un nuevo comienzo.",
    "El éxito es caer siete veces y levantarse ocho.",
    "Hazlo ahora. A veces 'después' se convierte en 'nunca'.",
    "La energía positiva atrae resultados positivos.",
    "Tu historia no ha terminado, solo estás en un capítulo.",
    "Sé el motivo por el que alguien sonríe hoy.",
    "La determinación de hoy es el éxito de mañana.",
    "No hay atajos para ningún lugar que valga la pena.",
    "La paciencia y la perseverancia tienen un efecto mágico.",
    "Enfócate en el progreso, no en la perfección.",
    "La vida es demasiado corta para no perseguir tus sueños.",
    "Sé amable contigo mismo, estás haciendo lo mejor que puedes.",
    "El cambio comienza al final de tu zona de confort.",
    "Tu mente es un jardín, cultiva pensamientos positivos.",
    "La felicidad no es algo listo, viene de tus propias acciones.",
    "Haz de la excelencia tu hábito diario.",
    "Los desafíos son lo que hacen la vida interesante.",
    "Cree en ti mismo incluso cuando nadie más lo haga.",
    "El mejor momento para empezar fue ayer. El segundo mejor es ahora.",
    "La consistencia es más importante que la intensidad.",
    "Cada día es un lienzo en blanco, pinta algo hermoso.",
    "No dejes que el ayer ocupe demasiado del hoy.",
    "La fuerza no viene de ganar. Tus luchas desarrollan tus fortalezas.",
    "Sé el héroe de tu propia historia.",
    "El éxito llega para quienes se atreven a empezar.",
    "Agradece el hoy, confía en el mañana.",
    "Tu viaje de mil millas comienza con un solo paso.",
    "La actitud es una pequeña cosa que marca una gran diferencia.",
    "Nunca dejes de aprender, porque la vida nunca deja de enseñar.",
    "La vida es un regalo, ábrelo cada día con entusiasmo.",
    "Sé paciente, las grandes cosas toman tiempo.",
    "El fracaso es simplemente la oportunidad de empezar de nuevo con más inteligencia.",
    "Mantén la cabeza en alto y el corazón más alto aún.",
    "Cada mañana es una nueva oportunidad para reinventarte.",
    "La pasión mueve montañas.",
    "Sé la razón por la que alguien cree en la bondad de las personas.",
    "No compares tu capítulo 1 con el capítulo 20 de alguien más.",
    "El esfuerzo constante produce resultados extraordinarios.",
    "Hoy es el mañana por el que te preocupabas ayer.",
    "La vida comienza al final de tu zona de confort.",
    "Sé valiente lo suficiente para empezar, fuerte lo suficiente para terminar.",
    "Los sueños no funcionan a menos que tú lo hagas.",
    "Cada día es un nuevo comienzo, tómala con ambas manos.",
    "La positividad es una superpotencia.",
    "Nunca subestimes el impacto de un acto de bondad.",
    "Tu futuro se crea por lo que haces hoy, no mañana.",
    "La resiliencia es la clave del éxito a largo plazo.",
    "Haz que cada día cuente.",
    "La mejor inversión que puedes hacer es en ti mismo.",
    "Cree, actúa y logra.",
    "El optimismo es una estrategia para hacer una vida mejor.",
    "Nunca es demasiado tarde para ser lo que podrías haber sido.",
    "La dedicación y el trabajo duro siempre dan frutos.",
    "Sé agradecido por lo que tienes mientras trabajas por lo que quieres.",
    "Cada desafío superado te hace más fuerte.",
    "La vida es un viaje, disfruta del recorrido.",
    "Tu potencial es mayor de lo que imaginas.",
    "El éxito es un viaje, no un destino.",
    "Mantén la fe, lo mejor está por venir.",
    "Sé audaz, sé valiente, sé tú.",

    # --- Bloque 2: Nuevas frases cortas motivacionales ---
    "Avanza con paso firme.",
    "Haz que suceda hoy.",
    "Tu único límite eres tú.",
    "Confía en tus capacidades.",
    "El momento de actuar es hoy.",
    "Aprende, enseña y crece.",
    "Siembra esfuerzo, cosecha éxito.",
    "Paso a paso se llega lejos.",
    "Sé constante y vencerás.",
    "El entusiasmo todo lo transforma.",
    "Crea la oportunidad que buscas.",
    "Acepta el reto con ganas.",
    "Transforma tus ideas en realidad.",
    "Tu dedicación marca la diferencia.",
    "Cada detalle cuenta.",
    "Construye tu propio camino.",
    "El aprendizaje no se detiene.",
    "Trabaja duro y en silencio.",
    "La valentía no se rinde.",
    "Vive con propósito cada día.",
    "Que tu meta sea tu motivación.",
    "Descubre de qué estás hecho.",
    "Mente positiva, vida mejor.",
    "Supera tus propias expectativas.",
    "La voluntad mueve montañas.",
    "Confía, persevera y triunfa.",
    "El foco crea resultados.",
    "Visualiza tu meta y avanza.",
    "Supera cada obstáculo con actitud.",
    "Evoluciona un poco cada día.",
    "Hoy es tu oportunidad.",
    "Dale valor a tu esfuerzo.",
    "Sé constante en tu propósito.",
    "No sueñes tu vida, vívela.",
    "El cambio empieza en ti.",
    "Enfócate en tu crecimiento.",
    "Tu actitud abre puertas.",
    "Hoy superas a tu ayer.",
    "Atrévete a romper moldes.",
    "El compromiso trae logros.",
    "Donde hay voluntad, hay camino.",
    "Hazlo posible hoy.",
    "La constancia abre puertas.",
    "Tu disciplina te levantará.",
    "Sigue adelante siempre.",
    "Manten la vista en la meta.",
    "Crea valor en todo lo que haces.",
    "Suma pequeños triunfos.",
    "El futuro se construye hoy.",
    "El esfuerzo no se negocia.",
    "Gana con paciencia.",
    "Sé el autor de tu destino.",
    "La superación es personal.",
    "Apunta alto y no te rindas.",
    "Sé mejor cada jornada.",
    "Que nada te detenga.",
    "La paciencia construye grandes cosas.",
    "Mantén viva la ilusión.",
    "Enfócate en lo positivo.",
    "Sé tu mejor versión.",
    "La excelencia es un hábito.",
    "Comienza con entusiasmo.",
    "El éxito requiere constancia.",
    "Cree en tus sueños hoy.",
    "Toma la iniciativa siempre.",
    "Demuestra de qué eres capaz.",
    "Persiste hasta alcanzarlo.",
    "Sigue intentándolo siempre.",
    "Tus ideas valen oro.",
    "Transforma cada día en oportunidad.",
    "El esfuerzo siempre rinde frutos.",
    "Afronta los retos con coraje.",
    "El valor se demuestra actuando.",
    "Sé perseverante y lo lograrás.",
    "Da siempre tu máximo.",
    "Donde pones la mente, pones el resultado.",
    "Toma la delantera hoy.",
    "Lo imposible solo tarda un poco más.",
    "El entusiasmo es contagioso.",
    "Sigue construyendo tu futuro.",
    "Tus metas son posibles.",
    "Sé fuerte ante las adversidades.",
    "Actúa con decisión hoy.",
    "Haz que las cosas pasen.",
    "Tu esfuerzo diario vale la pena.",
    "Busca siempre la excelencia.",
    "Construye algo grande cada día.",
    "Nunca dejes de avanzar.",
    "Camina con convicción.",
    "Tu dedicación habla por ti.",
    "Llega tan lejos como sueñas.",
    "Supera tus miedos hoy.",
    "El conocimiento es tu fuerza.",
    "Cada día trae un logro.",
    "Supera tus marcas diarias.",
    "Da el paso que falta.",
    "Trabaja hoy para triunfar mañana.",
    "Sigue tu visión con firmeza.",
    "La clave es no rendirse.",
    "Tú construyes tu éxito.",
    "Sé la fuerza que te impulsa.",
    "El aprendizaje constante ayuda a crecer.",
    "Visualiza y hazlo realidad.",
    "Actúa siempre con valor.",
    "Cada reto te fortalece.",
    "Procura ser mejor siempre.",
    "No mires lo que falta, mira lo avanzado.",
    "Hazlo bien desde la primera vez.",
    "Construye metas claras.",
    "Enfoca tu energía con sabiduría.",
    "Que tu meta te guíe.",
    "Avanza con determinación.",
    "El trabajo bien hecho da paz.",
    "Confía siempre en el proceso.",
    "Crea con entusiasmo.",
    "Tu constancia dará frutos.",
    "La pasión te moverá siempre.",
    "Afronta el día con ganas.",
    "Aprende de cada experiencia.",
    "Tu esfuerzo deja huella.",

    # --- Bloque 3: Más frases cortas motivacionales ---
    "Concéntrate y avanza.",
    "La clave está en no parar.",
    "Todo trabajo da su fruto.",
    "Sé firme en tus decisiones.",
    "Mira hacia adelante.",
    "Supera tus límites diarios.",
    "La determinación te guía.",
    "Toma el control hoy.",
    "Hazlo posible con ganas.",
    "El momento perfecto es hoy.",
    "La perseverancia gana siempre.",
    "Sé constante con tus metas.",
    "Crea oportunidades donde estés.",
    "Sé apasionado por tu trabajo.",
    "Aprende algo nuevo cada día.",
    "Hazlo con entusiasmo.",
    "No pares hasta lograrlo.",
    "Tu mente determina tu avance.",
    "Confía en tus pasos.",
    "La resiliencia vence obstáculos.",
    "Vive cada paso con fuerza.",
    "Tu foco define tu éxito.",
    "Mantén una mentalidad de triunfo.",
    "Supera las expectativas.",
    "Un buen día empieza hoy.",
    "Trabaja con propósito firme.",
    "La pasión genera resultados.",
    "Construye con constancia.",
    "Cada intento te acerca.",
    "Sigue construyendo tus metas.",
    "El entusiasmo lo cambia todo.",
    "Demuestra firmeza cada día.",
    "Crea buenos hábitos hoy.",
    "La constancia trae logros.",
    "Da lo mejor en cada detalle.",
    "La voluntad lo logra todo.",
    "Da pasos con firmeza.",
    "La paciencia premia el esfuerzo.",
    "Mantén tu ritmo sin frenar.",
    "Trabaja por lo que quieres.",
    "Hazlo hoy, no mañana.",
    "Busca la mejora continua.",
    "La práctica hace la maestría.",
    "Avanza sin dudar.",
    "Haz posible lo imposible.",
    "Confía en lo que construyes.",
    "Tus acciones te definen.",
    "Construye con paciencia.",
    "Suma logros diariamente.",
    "Sé imparable.",
    "Tu compromiso te llevará lejos.",
    "Mente positiva, soluciones reales.",
    "La actitud cambia el día.",
    "Hazlo siempre con ganas.",
    "Maneja el reto con soltura.",
    "Paso a paso se avanza seguro.",
    "Afronta los retos con visión.",
    "Cada día un logro nuevo.",
    "El esfuerzo siempre vale la pena.",
    "Sé perspicaz y decidido.",
    "Que tu metas sean claras.",
    "Haz que el día sea productivo.",
    "Gana confianza actuando.",
    "Sé resiliente ante el reto.",
    "Supera las adversidades.",
    "Cree en lo que estás haciendo.",
    "Crea soluciones efectivas.",
    "Toma la delantera hoy.",
    "Que nada apague tu chispa.",
    "Sé un referente de trabajo.",
    "Consigue lo que te propones.",
    "Avanza con solidez.",
    "Haz tu mejor trabajo hoy.",
    "La dedicación crea maestría.",
    "Construye valor constantemente.",
    "Conserva la calma y avanza.",
    "Rinde al máximo cada día.",
    "Que tus metas hablen por ti.",
    "Visualiza el triunfo.",
    "Actúa con claridad y firmeza.",
    "La motivación nace de la acción.",
    "Acepta el desafío con ganas.",
    "El aprendizaje te hace grande.",
    "Mantén el rumbo trazado.",
    "Progresa a tu propio ritmo.",
    "Gana con disciplina diaria.",
    "Enfoca tus talentos hoy.",
    "Cada logro requiere esfuerzo.",
    "Supera cualquier reto.",
    "Aprende y sigue adelante.",
    "La iniciativa trae oportunidades.",
    "Sé constante hoy y mañana.",
    "Trabaja pensando en grande.",
    "El compromiso es tu bandera.",
    "Sigue firme en la ruta.",
    "Aprende de todo un poco.",
    "La entrega trae frutos.",
    "Aprovecha cada momento.",
    "Conéctate con tu propósito.",
    "El progreso se nota hoy.",
    "Tu potencial no tiene fin.",
    "Supera el reto diario.",
    "Evoluciona con el entorno.",
    "El éxito favorece al constante.",
    "Crea cosas increíbles hoy.",
    "Mantén la motivación alta.",
    "La visión clara trae resultados.",
    "Afronta la vida con valor.",
    "Dale dirección a tus esfuerzos.",
    "Da lo mejor de ti siempre.",
    "Supera el día con éxito.",
    "Sé el protagonista de tu vida.",
    "Avanza firme y sin pausa.",
    "Gana con cada decisión.",
    "Disfruta del proceso de crear.",
    "El esfuerzo de hoy dará fruto.",
    "Mantén siempre el enfoque.",
    "Sé optimista en la acción.",

    # --- Bloque 4: Más frases cortas motivacionales ---
    "Construye tu propio futuro.",
    "Conserva la fe en tu talento.",
    "Muestra de qué estás hecho.",
    "Un buen esfuerzo nunca se pierde.",
    "Hazlo con excelencia y entrega.",
    "Sé constante en tu marcha.",
    "La determinación te hace fuerte.",
    "Trabaja duro por tus metas.",
    "Aprende con humildad.",
    "Hazlo sin pensar en excusas.",
    "Que tu meta sea tu motor.",
    "Mantén tu enfoque siempre.",
    "Atrévete a ir más allá.",
    "Supera cada pequeña meta.",
    "Aprovecha las oportunidades.",
    "Avanza sin detenerte.",
    "Haz de hoy un gran día.",
    "Persiste hoy y siempre.",
    "Tu disciplina vencerá.",
    "Mira lejos, actúa hoy.",
    "La fuerza nace en ti.",
    "Tu esfuerzo suma siempre.",
    "Sigue con determinación.",
    "Cada hora cuenta.",
    "El trabajo arduo da resultados.",
    "Haz tu parte con orgullo.",
    "Confía en tu evolución.",
    "Sigue aprendiendo siempre.",
    "Sigue firme con la meta.",
    "Sé apasionado en todo.",
    "Cada meta se alcanza actuando.",
    "El éxito ama la constancia.",
    "Da un paso más hoy.",
    "El cambio exige acción.",
    "Haz de hoy tu mejor esfuerzo.",
    "Crea bases sólidas hoy.",
    "Confía en tu progreso diario.",
    "Trabaja por un mejor mañana.",
    "Enfócate en crecer diario.",
    "Tu mente crea tu realidad.",
    "Haz lo que debes hoy.",
    "Supera todo obstáculo hoy.",
    "La voluntad lo puede todo.",
    "Sé firme y sé constante.",
    "Mantén los ojos en el objetivo.",
    "El trabajo da recompensas.",
    "La constancia hace milagros.",
    "Tus ideas valen el esfuerzo.",
    "Progresa un poco hoy.",
    "Sigue tus convicciones.",
    "Con actitud todo se puede.",
    "Siembra buenas decisiones.",
    "Mantén arriba el ánimo.",
    "Confía en tu propio esfuerzo.",
    "La constancia asegura el éxito.",
    "Trabaja con ganas hoy.",
    "Afronta la rutina con ánimo.",
    "Que nada nuble tu visión.",
    "Evoluciona en cada paso.",
    "Confía en lo que vas a lograr.",
    "Hoy es un día para ganar.",
    "Transforma retos en oportunidades.",
    "La perseverancia da frutos.",
    "Supera el nivel de ayer.",
    "Avanza paso a paso siempre.",
    "Ponle ganas a lo que haces.",
    "Visualiza tus sueños siempre.",
    "Rinde con excelencia hoy.",
    "Dale valor al presente.",
    "Sigue caminando hacia adelante.",
    "Haz que el esfuerzo rinda.",
    "La actitud lo cambia todo.",
    "Sé fuerte y sigue adelante.",
    "La disciplina da resultados.",
    "Hazlo hoy sin vacilar.",
    "Trabaja por lo importante.",
    "Sigue persiguiendo tus metas.",
    "Enfócate en solucionar.",
    "Mantén viva la pasión.",
    "Evoluciona cada día un poco.",
    "Avanza seguro de ti.",
    "Sigue aprendiendo del camino.",
    "Haz de tu trabajo un orgullo.",
    "La firmeza logra metas.",
    "Cree firmemente en ti.",
    "Procura el mejor resultado.",
    "Visualiza el objetivo diario.",
    "Sé el cambio que deseas.",
    "Busca siempre soluciones.",
    "Avanza con mentalidad clara.",
    "Demuestra tu potencial hoy.",
    "Construye lo que sueñas.",
    "Sé disciplinado hoy.",
    "El optimismo construye.",
    "Gana fuerza paso a paso.",
    "Cada reto es aprendizaje.",
    "Llega tan lejos como quieras.",
    "Dale sentido a tu trabajo.",
    "No te rindas nunca.",
    "Trabaja hoy para brillar.",
    "Que tu meta te inspire.",
    "Cada acción cuenta hoy.",
    "Haz que cada minuto valga.",
    "Cree en tu propio camino.",
    "Da lo mejor de ti diario.",
    "Confía en tu habilidad.",
    "La paciencia dará fruto.",
    "Trabaja con mente clara.",
    "Sé valiente ante el desafío.",
    "Sé perseverante hoy.",
    "Siembra hoy, cosecha mañana.",
    "Sigue luchando por tus metas.",
    "Avanza siempre con solidez.",
    "Haz de cada día un avance.",
    "Tu disciplina te distingue.",
    "Rinde al máximo siempre.",
    "Supera las expectativas hoy.",
    "Gana terreno día a día.",
    "Tu constancia es la clave.",

    # --- Frases sutiles (doble intención: calidad > velocidad) ---
    "La excelencia no tiene atajos.",
    "Hazlo bien… o hazlo dos veces.",
    "La prisa es mala consejera.",
    "Más vale lento y bien que rápido y mal.",
    "La calidad nunca pasa de moda.",
    "Lo que se hace con prisa, se revisa con calma… y se corrige con tiempo.",
    "Velocidad sin precisión es solo ruido.",
    "El buen trabajo se nota… y se recuerda.",
    "No todo lo rápido llega primero.",
    "La paciencia también es una forma de eficiencia.",
    "Mejor una vez bien que mil veces a medias.",
    "La prisa no construye, solo apura.",
    "Lo bien hecho, bien parece.",
    "La calidad se nota cuando nadie está mirando.",
    "No se trata de llegar primero, se trata de llegar bien.",
    "El detalle marca la diferencia.",
    "A veces ir despacio es la forma más rápida de avanzar.",
    "La verdadera eficiencia empieza por hacerlo bien.",
    "Lo urgente no siempre es lo importante.",
    "Un trabajo bien hecho ahorra explicaciones.",
    "La prisa es el enemigo silencioso de la calidad.",
    "Hazlo con calma… y que se note.",
    "El tiempo que se invierte en hacerlo bien, nunca se pierde.",
    "La calidad no se improvisa.",
    "Mejor prevenir que corregir… y volver a empezar.",
    "Lo rápido se olvida, lo bien hecho permanece.",
    "No hay gloria en terminar mal solo por terminar pronto.",
    "La velocidad es útil… cuando va acompañada de acierto.",
    "Hacerlo mal y rápido solo multiplica el trabajo.",
    "La calidad es la mejor forma de ahorrar tiempo a largo plazo.",
    "Un error por prisa cuesta más que una pausa por cuidado.",
    "El buen hacer no entiende de relojes.",
    "Más vale un resultado sólido que diez a medias.",
    "La prisa deja rastros… y no siempre buenos.",
    "Hazlo una vez, hazlo bien.",
    "La calidad no negocia con la urgencia.",
    "Ir despacio no es perder tiempo, es invertirlo bien.",
    "Lo que se hace con cuidado, se defiende solo.",
    "La eficiencia real empieza por no tener que repetir.",
    "No todo lo que brilla por su rapidez vale la pena.",
]