LOGO_TEAMCELL_PERSONALIZADO_B64 = """
iVBORw0KGgoAAAANSUhEUgAAAZkAAADpCAYAAAD28Eq7AAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nO2dCXRVRZ7/HxjtsMR0ICz/EZooUY6n7QbabuLCjoBN2ASaZgkOTKJnhAYEDY5CK/SA04CADWOcaaFxZElEUITEAVqWJKgsKkHP6Z5I2BeTEBNCQoJC8/7n+zrXvj7ztntv1a173/dzTh2W9969VXXr1rfqV1W/XxOv19vX4/Hs9RBCCCHWsqApK5QQQogoKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBEGRYYQQogwKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBEGRYYQQogwKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBEGRYYQQogwKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBEGRYYQQogwKDKEEEKEQZEhhBAiDIoMIYQQYVBkCCGECIMiQwghRBgUGUIIIcKgyBBCCBFGDKuWGKW2ttZz/PjxoL/u3Lmzp2XLlqxjC0Gdo+412rdv72nXrp07CqfDv5xoR2hPdnP06FHb82AWme8lRYaERVlZmefjw4frP/7448qPDnx0fefOXZ2M1lxSUqeq4cOG1w4aNCixT9++zShCwUFHm79vX31OTk7F+g0bOgb6ctrEiWfHjRuXmDp0aDNFsh4RKOfWre9U/fGPf/xbYeH+xEC/TU0dcn7cuHHNR458JEFG24HYZb3yStlrq1+7taam1pF12xh4Dx/LeOxv6RkZiUIHKV6vt6+XED9KS0u9udu3182YPv1MUlKnSjQVUSklpUfp/BdeOLe/sNBbU1PDR6EjK+uVS3FxLesiqXt8P3vjxnplChEGRsuJ34nKE9ri7FmzSkW2fVWSwHqcT5Eh34KXCo1NtKiESr169bwIgYtmwYHI9+vX9ysz9Th61KiLqtch8me2nPg96stKSkpKfO0wGgRGcHsxLjJFRUVeGaNcN6TU1CHn0Gla/fSsAi+oqiM25MvqDkR10MFFOqoPlJKTO1/C9VTEynLiOlaVEx0t6i0a+6qM9PSLFjeVyEUGDwCKF40PwGxSzYyhDRScUHcyxAZtGya7ZcteOqVP69a9USlL6ER0cLieajMalcsZ7f2bxaazyEQGI4VoVXgrExqxnaNz3NupL5IIsQl3Jpc2ceIZCLNIRD0XmJRUEpqxv/pVlYhymh2J4/m6pZ8xmlq0aH7FwncsfJGxcmrLZO30PlzQySxauNAVozSMtqzoNAvy869E2q6nTJ78pYgOG3kRWWdzMjO/sjzTBhBdTlzfaN5GjhgRFQv94bxfFj3u8EQGL1S0LYLJSPHxt9bLGl3ixcP93FR/mFWbmVlgnczovVGXVg8SZFgJMMiwNNMKlhPXN5IvjN7d9H6YSVhrt+hxhycybhn9qphgprHoYTYKRAwmBDfXIdpnpGINgTB7X8yArDIryDTT2LkJRVY5jQwAsB7n5vck0mRR2w4tMlR3xzzM7xFNa2iYaUfSsVhVL1jrsOJZ4ZyQzPoyY1Iyg6yNJkZmbNjkEQ3vSrjJovXH+SF9l/35z7uqxB0FJaLquLCgoK579271JSXH46OhknFCHOVFuUN9Ny8317J62bt3X6uc7OyrZq8DLwpW5CdcUoemNgnlEkgEBw8dvEXGfQoKC65ILxxpnFAzGZzxiHZFF51Qx1YMGTTMrDW4IYUyB2Hh3spywmxmdm3Njnq30tynWjlRtkjzxpnMd5O0mUxBQUEr6rNYrKxjjNKHDhvmGv9KRkD5X1y0qCLQT/fu2/sDK+8Hf1bwuSWiLCJBvsePH1epd0LpFtzkY8wu4HjVCkKKDB+WeKyqYwrMP5g7b17iM3PmVDb22alTpxOsvt/OHTsd2VPD3Dd8+DBXCg0xDpxnWuU0k/FkXAIF5vssWbq01auvZlXLuNe7294N6DVYdSA0//673zUqyCQ6gXdmqwoeUmTi4lrWs52JxWwdU2ACM3XqtHjUj+j7OH3GD0EONPMj0Qfc/1tV6JAiM2L4iIC2bWINZuqYAhMa1I+MQFOIueNkIDRW7JQjzmbRwoUVVsaXCSkyCILENiMWo3WMjpMCEx69evWsF71lt7S0VOj1ZTB+woRYGTM/oib9+vWtfG7uXEv7/JAig8iFNJmJA3WLOo70Blio7dOnN0edYQJz1sMPD67mAndoMHCx4wwNsRcIzLZt2y3fTRxSZBDedPHixd/w+YsBdWskhOzkf/7niurqy7HOKKUa4ABm9+7dhG0EcFMYaRxspdBEDzCR7dmzt5WQNhyuF2Y6yLQ+GY1/QV9yaiYzqFgmEQ5cZeY/UqLtMCYOrEqI0zQ/JlwxWrv2dZ/bDp6bsQaYyXbs2Bkf6cgBblNwBkTdkhG3gJkyztDAhOKmWZoKpKT0KHvu2ediWrdu3frgoYOnZWYppUdKp5ZxcZ6uXbuiLxffnzNomfxkNCY5RpVuc9fvpmQGlesBgdRMFU6HzHxHisyZDO5lVZ0qTmi3Mno6d+7sOXKkKB72O+Hq51K0xTUjWwRfeP75Mq7DENlsefvtgN4TCAlF2OYyDUybscUtPSPD5z04Lzev6sDBAwkiXHW4DU1gjJgesAi7fMUK6zavW8wdd9zu6d+v//cuunrNGlWzTCIAZ2ji4+MrrN7eSqKASMxlTsaKIFVmktkY6yqFhb3jjtu9r2ZlVW7ZvPnUmTNnztXW1gaNonft2rU6fC8nJ7t0zOjRSpRBRDKDU8poNuCZys+D5jIhhB/j38nYHT46ISHhqhmBkRk1MVgaMKC/94P9+01vRYEo5eXmXsT1VCiXVckMTiqnGaFR+XlQZIQQ2ZqME8HhO+yQQVArO7KPXWSHDx/+gZndOS8tXXrW0kxFyIAB/T0f7N9f9v77uz0PPPigaZNdixYtEoakpibu2LGzbv36dVIcWBLr+PW4X3t5hoaEi6tFRhMYeJm14/4QmCNHipphw4RR4A9r/YYNHe3IP9ZZ8nJzK6wSF39iYmKaT5yYFl9TU1P94qJF9CrhEK5cqWvOw5okXFwrMm4QGLBk8WJbvC6OGT3ac+DAwQrMOETfq2XLlvHPPvdcs7KyskoIG1EfnJebMmVyBd30kFC4UmQwwhoy5JcVThcYvMB27CiDwGTn5NS3adNGqomxbdu2rY4e/awa9yfqAxM0A56RULhOZCAwmMrbuQZjhcCA/H37pJuQYLZ6a/NmmLJs8eyAWQ0EjkLjDDCQm/Xkkzw3RwLiKpHRBMYu1zdWCgzIycmR+vLOycysg9lK5j0bAwJHoXEOq9es4WHNCDl/7nzUHKpugi3MGJAokBdTuE1gYIKIi4uz5FrhoJnI7JrBNEZtbW11164/jT9x4qQqWQrK33foGqNJkyZqFioCsrJeqX7iianxwX4hs5yRPo/ly5edfuqppzsJy5Af8F/2wx/+0LJwHV3u6tJ00KBBiQgdopCvuQWuOCeDg5bwKGrXuQHcG3mwkv2FhdLyj8OVNTU1l+x+jo2Bczl2PVfR5zL0OKWMoVKoMzQqPw+3eGFGf5SV9YohD+8CcP45GbtnMMDKGYzGpk2bpJ2NWbVyVQXWQmTdLxKwdTojPV3FrJFGQMAzeApn3dgH+sKpU6f5YiepsM3c0SKjgsDkbt9eb7XAgLWvr5WycQEduIxtymZ48T/+gwvLDiJ1aGoTnqGxn4YgfbafZ3KsyCAOeXJyssdugUkdOtTy+6NRyCrX3HnzbDmHEwnYSs3Dms4BbZeHNdVAexY41G0XjhQZCAym5XbmQZTAgP/761+ldKiYxSQlJSnr2VnP9BkzGALcQfCwpjrgWUybOtU2a4DjRMbtAgN27dolpUHMfuopW32iRQLWjDibcRY8rKkOiAl09OhRW+7tKJGJBoEBxV8U3xB5fU+DX7K7777bFp9oRhk/YcJlJ+WX8LCmSvxpzRpbBpWOEZloERiwc+cu4Xv1M9IzHDcrgGkPHqGJs+BhTTWQtZnIH0eITDQJjCz6DxjgyNHlmNFjqhTIBokQRNbMyc627OAhiRyszdixAUB5kYk2gZFlN01OTr5Fyo0spk/fvjTwO5TxEyZEjSsVVSktLZWeM6VFBiMfzmDE0Lp1a0fsKvPnRz/6kTL+MgghoVFWZGDDtXvk41aBcfK6BqJqKpANQhyJHT7NlBQZCAxsuHbmwS6B+fzzz4SvOdyexMBghEQbcOIrwjtJKJQTmWgWGFBeXs5tuoQQyxkxfIQtm32UEploFxhCCBHF05mZtpyLU0JkcCL4sYyMCgqMLyZEWzvvT9wP2jkfc3QxcsSIsq5du9pSZttFBgID1xM4sGVnPlSZwXTo2JGzKCIUtHMKTfTQokXzupeWLbNtN6mtIqMJDFxP2JmPOZmZlaqYyGTs/tizd4/wexC1QXtHu+djcj9v5rzZxI4Ffw1bRQY+jVQQmMVLltiaBz0yGoNTwhk3xldffaV8aAKngHZPoXEv2E1WkJ9fZ/cA2jaRwUl+u01k/fr1VUpgZHLhwoXTTsx3SUkJXf5byG+ff74V3gPXFIj4mD1rVtmxYyXNevXu3dzuGrFNZJ6c9aStnQVerG3btkelwICzZ886MpbQnt27lY7i6TRgnsV7QKFxNklJnapSU4ecX7fujSq4jlm2fHm7du3UcOphS0eDiHkIDWrHvT06gbHj9Gs4DB48SPgs461Nmxzl5l9j957d3BhhMXgPsrNzWsG84qqCKcyUyZNLvV6vx6p08uSphNzcvNvS0iYlqCIuGraIzEcffWibJ13VBQbExMTEiL7HsuXLPVeuXHGUR+NTp06V7d7NTQsiQMd05EhRMwqNHO75yT1fR0M5PXaJjF2n2p0gMKB///7XZdwnf9++v8m4j1Vkb9x4q5Py6zSw6aSwcD9nisRSbBGZPXv2CB+p++MUgQEpPVKEBy0Dy1csd8z6Rm1tbfVzc+eyAxQMDuzxDA2xEkcu/kaKkwQGJN95p5T7wPQEE5SUm5lk1cqVjox/40Sw5TV740YGGCOWYIvIyDIHeRwoMJ4G+3hKSg8pnX/m008rH1fm4sWLFZzFyGXc+PGxPENDrMAWkbk55mYpcWKcKDAaw4cNv0nGfTZv2eJ5Ly9P6VDMzz37LLct2wDOkGWkpzsyTDdRB1tEZkhqqvDRs5MFBvx63DhpHev0GdMTy8vLlRy1btiwvnr1mjUK5CQ6WfHyy4k8Q0PMYIvIYBcLDg+Jur7TBcbTUEeytpPCzcz999/X6tq1a0rZ4U+cOFGRljbJtvNU5B+HNXv16skZDTGEbQv/c+bMEXJvNwiMxpTJU6S92BCaCePHx16/fl2JnUWYWQ0c+BDNZAqAd2nt2tcTeYaGGME2kZk06dF4qxutmwQGjB07VuqpfKzPjB83rpndQgOBwczKyY483QZm1jysSYxgm8j4XFlszLbsepjOu0lgwIM9e0q/J4Tm4YcHN7NrjQYmMgqMmkBo8nLzvNFeDyQybD0nY1VMi4SEhK8xnXeTwGikTZx4VvY9cX4GHX1hQYFUocEif+fOnRMpMOoCr748rEkiwfbDmNgmuWjhQsNrD9hieebMmR/YGZRHJPMXLLDFkSU6+t59+rR6Zs6cOpy2F3mvo0ePVjz00AAPF/mdAQaHWVmvCG0TxEV4vd6+XgUoKiryJid3voQshZNGjhhRit9EA7NnzSoNt15EpDvuuN27fv26S9euXauzsrpPnjxZmpGeblu5rE5mcEo+9czJzPzKTc9j2bKXTsnK25TJk7+07EGozXxlREZjf2Ghd8b06WcGDx50KimpU6X+weDf+CxaxEWjpqbGGxfXss7ulxZi8+KiRXXl5eUXzZTnzJkz5+ZkZl5RuYOS0anpcUo+/Rk9atRFtzwPmSKjQkKfgn520cKFF0tKSixtFzrUExnSOFlZr4Q9y5ORBgzo7301K6sSghFshlNbW+v7zpbNm089NXu2q19aMzgln/5gANSvX18lZzSREm0i458EWYfmN4HIeDyevTSBqk1tba2nQ4fbrlZXX5bikscIAwb099yedLvvl5cuXfLtVIsm/q4VxmjSpIm0mjKTz8ZA2+zevVu1nYEIGyPSci5fvuz0U089LcUDusrAOSp811mUxQXSXe4TY2Dn3Ib1G7xDhw1TtgYZUCw6QdvcsWNnfPfu3epramrpyNThjJ8wIRZHCZ6bO9eSw9BR4erfLWBXD917EBXRDmvy4biDufPmJRYWFNRZURiKjMNYteo/6WqFKAmEhmdo3MOw4cOawhRqFoqMw0DkQjPniggRCWbbFBp3gPXfdeveMH0eiiLjQGbMnJlIs5kx6LZePFZ58iD2s2TJkhtmM0GRcSCaV9wWLZpbYjONFjQHqtFeDzKAJw8KjfM5dep0QlmZuSC9FBmHAvv3mzlvytv36nDgPTg7O8dVDlRVB0LDmaPzKS0tNVUGpUTm6NGj30lWLDq5GZglsKc92ushFBAY7Hxq1054QFbDiAzip0e2q37MHO0QGoYksI6C/HxTUxlbRQbTsKdmzy7r0KHDVziM1q1bt++kuLg4z6S0tLN5ublsMAHAoSmaJQKjCYzqDlR//OMfSzF9jhg+QupanhZZMz7+VqmDod69e/OdsIiEVgm3mLqSHW5l4IoiUqePvXr1FOlfx/Go7qzQjgTfTI21GVF5McO6dW9Uyqgj3MeOto7nINP/npFyynoGTksmXc3I912GxhYff2u90YqGMzeIFPk+FJp/pEAC41VUZEpLS6XUiZ3vDp5HixbNpThGRX0ayV+0vB+i61KHXJH54osvamJjY2vNFhoO+Sg0jZO7fbvt3prtTsEExquoyAC4fxdZd3CyajqTJpHRPuEZ2mgub7vttopof3/0CRYkk49cnshADa2cLptpSG4nmoUGMYlCmVVFmW3MInI2g3pRZWAmun2aGXmr5u3c7mSBeVWeyIiIO5G9cWO9jLw7Edk2cBVSuDNcxNAQkV8rENUBqxaDSVQ5zfYJaD9mzPluShYNTOSIDBq4iMpHJyo6704GIzqVg0pZmbAeFe4LgXU9q++fmjrknFVNxeq1NXToKjZjq4UG9WZFvgry810XUM9IsmhgIkdkEM1SVEWo+gKpBEZ3shZcZSeUK9LRq4gFXqvboVUdsOrvB/JnRdu0er0p2tc2LWw3ckRGZGVAwETn3w24cVaD8hi1vyMKoFX5ELXegZEkrm0kT07a8o98Ir9G616UKdAqAXRSgqkQMzkLq1G8yIgylWkJcf9F5t9tuGFWg47F7EjLyu20otc7UNZwxcaKurELFcuJQUykZ/qcmLD0gHIKGCyJD7+8auXKshkzZwr151FSUuJR/US3SsDTwpLFi8uWr1ihrp+VRkhO7lz98oqXb4E7HSuuB08SQ4cNM3UtuLW3Kj+hOH78uOe9vLyynbt2Xgfa17vc1aXpL3r8ouX99z+Q4Ib3AOV8MyenoqCwAIMAz4EDB9rdd999ZTExMTGDBw2OGZKa2k52OfHO/PnPu6oOHzpcW/xFsWnPxKpw/333x/z85z9v1adv32aC/PotED6TWbbsJSE7efTJrlPMTkcbpam+C03kqBWmASO7iVBnFpsVCHEj813hhTknJ4cu7w0Ah5HLli9vd+HCl83WrXujCjMFlfKH/GCmcOxYSbyo2UKv3r2bnzt3Pnb2rFlhOwHEd48dK2mG34rIEyFuQri5bP36dVWTJj2aILrOampqPHTjbh6YkHJycirWb9jQ0Y77w6HllMlTKsaOHdvxwZ49pd4bXr/z9+2rL/6iuHzPnj0xmkkKZpr+/ftfT+mR0qlrt25sZ4SEzwLhIgOX/fCoLBqZtvFoAc8uLze34sOPPvy6oKCgVU1NreX1Cxf3PR/sWTv44cGuWVMghHyLeJEBcOMvmrSJE8+uW7/eltF3tIDFz48PH67ftWtXxcFDB285ePBQRBsHMEuBC3ZtVpB8550elWO8EEJMI0dk7rsvpSzSDskIiODGTks+2A0UKsBc165d3Vl4QkgwFsTIqJ5fPvzL6wcPHhJ+H2wxTEubJHz9h3wXmrgIIYGQsrvsoYceuk3GfRYsWOCK3XKEEOIWpHTKsL3LoKTkeDwWqwkhhKiBFJHBOklKSo+wzyGY4U9r1pyVcR9CiMfzwf79IdfjSHQjzbyEdRkZ91m5alVH7IIihIgF71nPXr08o0Y9otQh3mjjxUWLKh7LyKhQVeyliYysdRmwZvXqCln3IiRagYUC59Nmzph5CxuBfcDH2+o1axKxy1NFpOwuAzi9jXMSIg70+fP7xb9vMWPmTJ7MJo3i72jSaseL8Jqw6j9XlQf7DpxaDho0KPHnv/hFMydvu4+WA9BoM5vfeqvmmX/7tzgFsuMsZIVfBjJdZlsdxIg4n3BcySN0BCJnmnF5HmlbTZs48YxTYr9EK5oTVdXCWHt14cRVzJt0B5lTp02TNmTLzMy8mWszxNPgkww2a7j1xw7EYJVy6tTphLnz5iX+0z/9v3rMSMxUIFzynD9//rR/OnDgwNmcnOyyjPR03/fgJy45OdmTk519lQ9MTaqrL8dGex0YRuZMBhiNgGckYeYks2xEPRDOwEybMxI3XvttONTU1Fx6cdGiOqP3w+wMMyHMwLRrYGSL2VgksyPM3BAyQ38t7TrBoo/uLyz0RjLrQ35TU4ec09cx/o17+98H1/3v//6vq43ldeUf/lCqL59/PSAUg3ZdKwJxaXm1craAfGn5TknpUarlO1C9o7yNhZcINJPBv+e/8MI5fK4l1AnqzmhEWQPICb+sR3bsbJohohc8eyti5eCFj6QSIxEZjYL8/K+034UTOwedTThRJBFmOtQ7gM+DxdRBBNHG8oSOCp/369c3pDCGG0oaZm5NFKZMnvxlY/WhRdtF5xzOda0IKWy1yCBCbThtMyM9/VvTrSbO/s/TX2TwZzgDKzPhyyNAvsigwmQGycJLJrN8RA3QzozGx28sRdK5GBEZr05o8H4EG31D9LR7PDV7tvcvf/nLGf3ntbW1lQcOHDiTkZ7+bV4CCRfuoxeYGdOnn8HsBOXFb/SdVWMj5XDKqh9YYtZ25syZc/rPr127VvfB/v2lAwb0930Hzw0dqdZ5IvBhY/f1D5+tzzv+xL/1n5sRGqtEBvUN4dDXR3l5+XcGMXh+ebm5F7X6wPPR14d/HvT/71/X/tf2r2u0NcEDcfki45W8AcBs4yLORN8RW5HQ8YVbEUZFBmjCEGjjCsxp+PyOO25HpxJyhgXhwncDCQ3MSVqHHaiz0e6JkbT+/8MRGe366NT8O7zGQOeqdX6a6SuQyGgJM6lAI3K9uRSdtVHTmVUig9kDrjNm9GifqTTYd69du3ZFM6WiPrRBUyCRef63v/1au3Y4db1q1cp6CUJjj8igQDJFxkzjIs7DvxOyKoXbwZgRmZMnT/oGYOhg/T/DYEkTmLKysrDXbvBdTUj8O2PNBAPbfbBrYGDov14USmS0/EJgMIION79602EokYGAhHq38bk264nU9Klhhchg4KCJQCT1oV+zCyYyRupaE3UImKA+0h6R8UreAGCmcRHnYaWZTJ9CdcQaZkQGaKYM/9GlVi50DJFec/36db7f+m+GCWSSCodgIqM3wx0/fjzi/Oo71mAiE26nr3XwjYl3OJgVGf0yQTizDH/0ps9gIhPJ4EMj1OzZJPaJjOwNAGZHIcQZaJ2JiISXOZxKMCsyWgcLU5P2f1hj0EaqRsEMCB2d/ufauoWR2X4wkdHeb3RgRoApKZTIRCIY2iYFo8/FbB+imQ3xbI38XpvhBhMZo9fW6tq/bViE3HMyevr07dsMHgBk3nPMmNHVdObnXnAuaurUaUHPwZihuLj4VhmV16VLF5+3gPLy8sva/23atMnn+HX2rNmGXSZlPp1ZBY8bek/lM2bO9EWTxTmQDh1uu7p+/boqK96RnJwcXz4zHnvMkMPali1bxmvniALRpUuXy0G/oEPvVcEO9ys5OTkQXdTHFSO/T0pKajdm9Oig3xn5yCOG2gbqGtf2bxtWYZvIwOXL4sWLv5F5TxzEm/Xkk/Rr5lKmTZ0q9NnioKZdNVf8RfEN/BkTE/P1hQsXTkeazp49e76oqMjnY+zzzz+r0q4LNzoF+fl18fG3XoXQTJr0aEJcXJxnUlraWTOHUd/d9m4i/rznnnsM+3a69957q8L4WsTYMdDMy3vP57uxTZs2iUavMWDAgKD1cffddxsOPz/mV2N8J9f1bcMqpPkua4xJkx6Nf+aZZ6T4M9OAI7mRI0fWR4vPpWjh1Vezqre8/bbhFzgckpI64QUULjTl5eUBZ0yDH37YckezvXr3bn7u3HnPunVvVC9ZsuQGxBReCNZv2ODzN4jBIN7VSHwBau90ixYtDNdX27ZtL8uob6cgsj5ujrnZ522iYfZs6T1sFRltNjN16jSpHf7f3YuUMGywS8AUX6SZTKPngz1rZXR6u3fv9t2jy11d2jb2+fwXXjgfd2vc9arKqr8d/vjwTV1/2rWuXft2zUNd9/y587GtW7e+KS1t0vfEGO/iE09MjX/iiam++kRcJoTNgFjg/Xz22WevfvLJp7F8Z0ik2CoynobZzNy5876uqqr6gcz73nvvz66eO3c+lp6anQ3s67169YRZR/hAZdy4cUJnSuDKlStVm7ds8YkMPDRr/w9P0fhz9KhRFS/Mny80bEbXrl09f1i5suOiF1/0bN36TtVvfvObZjClRfLOIEjhwYOH2sFM17FjR0P5DTajcxqaB/rr16/Xx8TEGGqrH374Yadgn5u5dnFxsW9Ak9IjJeg9jGB7THw02HVvvHFD9n3x0gwfPqySGwGcC57dlCmTK2SYW9FJYLOK6PusXfsn3z1GjhhRpl+sHjdunG+m8smnn9wkOg8aeDfT0iYlQFiSkztX42zCB/UAAAvrSURBVJ2B6ITz25QeKb711rzc3JAzrEBs3rLZJ7YdO3a0vOOTzYjhI3zrhZ988omhdUMIyDtb3wn6HaPX9viWEVb72p2IUPm2i4ynISYFXirZ9927d1+rf//d7ypl35dYAwYJhYX7hc8uAMy6ome95eXlldOnz/B5+52/YMF3PJYPHDjI1+FivcSsd+hI+bsp7Qlsc/12l1Qo/iU93bcIvfSlpQnoICO954kTJyp2797j+/tdd3WRWVwhaLPg1a+9ZmhxftfOnVdOnDgZ9DsvLV1q6NoffvBBGa7tP7CxCiVEBry0bJktkZuWLF3a6pk5cyg0DgPPDIMEGbnGziuYdUXeAwJz//33+cqzaOHCCpis9ODlnz1rlm8gNjFtYhOrZuBP/Ou/Vq9auTLsAR6CvIXzPeQ/Iz29Ap3X0iVLIsoTROnxxx+TMniQBQbSvXr1rFi9Zg0C5kU046itra2ePmN6yPrYvGVLxNe+du3a1UmPTvL1vf4DG8uw6zBmY1jtbyqSFI7nW6IGstsJPOZGUvBID/3BYaHmXyyYq3/9Kfpg/rr0wLVLMNfuWl6D+a7SOxvVe84I5VYGv0M+I/FS8M0339TD7UqwQ9TafcM9HKth5kCl9lscijUK6lhzbwPXOeFcJpz60J/4j+TacD+jXdtISIswse/Ef2P4e4Sl0BB/ZHuKMOLFW/ttMBcfFRUVpeh49R1IOC+6PnwBOiy9a3w9EBW9t99AaM5qcc3G2r/ebby/77NwHGTqhWZOZuaVYE4h9WKLvGsxVlQSGdST5uk5VGoMffv9n/95/WowP2P+g49QIrNp05vftg04vwx2bbj60dwX4fkE8vaA523Sp5laIuPVOdWzK0U6aiXysMMVkRHvtJHeAx1DJO0OefL3/YeOBi5i9AGwtIQOO9C19CLgaXDVAqeZEFf/6wSK6xJMZBq7B8ITbNm8+RRCFOzcsePcq1lZlVqHByHT6iJYMC67RCaSFGjQgD5OG0xDROAOBvWhJX19eHQ+xTQBCebqH6LQWF1rKScnu9R/YBNMYHDPYCIUBuqJjFfnDtuuJHDqSAxih8AYdRgYTl7x8kIQ8F2jLzB+G8wZKIQinDAXuH8wE2SgwGeaeIT7vqA+A8WSwv9jVqWfKQUSenwnISHhqt63W7j3Dya4wcD9rBIZr67Og8XWQvvwj/45cOBD32uT+H/kT9+OQrUNLeBbMCJ9vgGY3wQig41WshbAwgE+qNq3b29rHuZkZlYuXrJEysIyCQ4WpmfMnCl1YwgWad97738TnXCOCmeF/u+vf60v/qLY5/MMZx2wFTXSnULYTHC0qMhz8NDB056Gw6A4qxPsOvhNpHX0wf79nk8//bTs2vVrV7X8du3W7TvXwXd69url2zp++XLN97aOG7mvmd+JRP/8bo65ObZ3nz7tcOi1sXxGmn/0paWlpXAdVJbQKuGWn/zkpwmBrt0Y2gYTE3W2QMmZjNfmTQBawoyKcWjsRW+LlpkYttteMHvyNBKagDgONc1lXgHhc40mk/ZIYuL5623LMpOguBokTPQDCwkx6IlY7HP1HwpMzzZv3iLcH1UocBaDngHkAvNB9+7dqmWdg9EDty3w4aVGTbgLPNedO3YELBN8pj0ycmQZzq7h31lZr1SLOBxI5KLkmoyeFxctqpg7b57tB7NwIC8/vyDW/5AcsZac7Oyr4ydMiLWjWmH/P3asJOgaBDEGBKRbt27f1vOUyVMqOiV1+tad1NatW1vovTfgQOpzc+e66kBmlKLumowGzCayQzUHSzSliAHP2a71Fy2FsxOLGEc7kxMs4V1nBFtXoebuMn+wQ+LOO5Olxp0JBnYerV37eiLdnlsDzChwdCnLD1ljcOQsB7zLHx8+7NtJdeTTI02rLlU17d+///W2bdveev/9DyTwnXIdCxwhMqCwoKCud58+hj26igA240iDOZHvAvNYxmMZN65cqbPt2fbr17dyz5693K5OiPUsUHbh3x9E70OnrlKeECgLC9Qi4mK7HdRZ7969KrD+YqfAYH0gOzuHAkOIIBwjMgC7fnBIUoGsfEtJyfF4LGhigwJ3oIUG5pKnZs8uQ53ZaR7TyMvN83KhnxBxOEpkwG+ff74VzBsKZOU7YAdchw63XZUd68NJIA5/58531C1fsUKJXh0zY8yQFcgKIa7FcSKD9Y9t27a3wpZiBbLzHRA5cOiwYc2w158mtH+AurjzzuRqmBftNI3pwYyY52EIEY/jRMbTIDSffPJpLOzpCmTne2x99912MAdhzSGaZzbwPwXBRV3ArKhAlnxgJky/dITIwZEiA7DV8ciRomaqCg3AmgNmNrffnlQFU1E0rNlgzQVlRZnh4BCCq0C2vgUCg5mwItkhxPU4ZgtzIBpckChzhiYUCKE7ddq0dm47DwCT2J/WrDm7ctUqQ3HGZaAJDLecEyIN55yTCYbThMbTcKDz8ccfv2ngwEEJTt7dBHPg6tWrL6s2Y/FnyuTJpStXrWpPgSFEKu4QGY9DhUYjJaVH2fBhw29KHTo0UXXfaNqJ7V27dlWsfX1tohPqm7GBCLEN94iMx88Jn1PRnAeOHTu244M9e9peCoj3Rx99WHX40OHabdu3tTx16nSCk6qWAkOIrbhLZDwN7mdSh6Y2ceKMxh8ITu/evSvh20mLmAdzj6j1HGxMgKh8/vlnVTt37Kx9d9u7jpipBIICQ4jtuE9kPA43nYULBOiBBx4ob5PYpmn3n3X3uUxHuNwOHTsGLTMEpLy8/DL+fvrU6abFXxTfuHTpUuzBg4dcdeydAkOIErhTZDwNQnPvvT+7igOSCmSHSIQelQlRBuc4yIwUmJTOnTsfq6ILGiKO3O3b6ykwhKiDa0XG0+AZAC7cVfPeTKwH5sOioiJP6tChrjWREuJEXC0yGvBRVZCfX6eydwBiHJw5gvcHhsYmRD2iQmQ8DfFo0BGhQ1IgO8QiRo8aVfHee//LKKWEKErUiIynYZ0GHVJGejqFxgXADLp5y5ZEnuInRF2iSmQ8Des0r61enZi9cePVFi2a1ymQJRIhycmdq7H+Qlf9hKhP1ImMxrjx42OPHz/RHOYWNXJEwgGzlyNHiuK5/kKIM4hakQFwTAlzC2Y13BSgNlhLKykp8c1eaB4jxDlEtchoYFZz4cKXzbhWoyaYvRQUFHJxnxAHQpFpQFurwVZn2PyVyFSUM3LEiDJt9hLtdUGIU6HI+NGw1TmeBzjtAyKPk/vvbN3quuBuhEQbFJlGwKwGo+fS0lIPTWjywLqYtrDPk/uEuAOKTBCwMQAmNGyXhelG2Yy6ADi1xLoYF/YJcRcUmTDAdlmYbmDC4XqNtcyeNasMM0Y4taS4EOI+KDIRABPOsWMl8fsLCzmzMYFmFoO4LFu+vB1mjIQQd+LaeDIyQLz7t9/eUr1kyZIbTgtLbAeYBb684uVbuN5CSNTg3ngyMsAIHGsIJ0+eSuDsJjBpEyeeRf1gFkiBISS64EzGYjC7WbN6dcXvF/++hZvDP4ciKalT1Zw5c5qOGjU6nuYwQqIW94ZfVoGjR496CvLzy97a/NZNhYX7XR+tEcIyfNjw2n9JT+9I32KEEIqMRLQZzmurX7vJLes3WMAfMXxExeCHB7ccOHBQAmcshBA/KDJ2AMEpOXbMc/DQwdN79uyJyct77zan5D0lpUfZ8GHDb0odOjSRsxVCSAgoMipQW1vrOVpU5Hn//ffPf3Tgo+s7d+7qZHe2ICaJiYnX+/fvf73LXV3adujYkeGNCSGRQpFRFcx2cI7k888/qyovL7985NMjTS9WXLxRXFx8qxXmNpi6HnjggfI2iW2adv9Z9xuakLRv395DsxchxCIoMk7m+PHjvlmQhiZI/kVK6ZHSqWVcnO/vcDjJk/WEEElQZAghhAiDhzEJIYSIgyJDCCFEGBQZQgghwqDIEEIIEQZFhhBCiDAoMoQQQoRBkSGEECIMigwhhBBhUGQIIYQIgyJDCCFEGBQZQgghwqDIEEIIEQZFhhBCiDAoMoQQQoRBkSGEECIMigwhhBBhUGQIIYQIgyJDCCFEGBQZQgghYvB4PP8flGWdVA27QnQAAAAASUVORK5CYII=
"""

# Frases motivacionales para el footer de órdenes "PARA REPUESTOS"
MOTIVATIONAL_PHRASES = [
    # --- Frases normales ---
    "Cada día es una nueva oportunidad para empezar de nuevo.",
    "Lo mejor está por venir, sigue adelante.",
    "Tu actitud determina tu altura.",
    "Los sueños grandes empiezan con pequeños pasos.",
    "Hoy es un buen día para sonreír.",
    "Nunca es tarde para ser quien quieres ser.",
    "Haz lo que amas y el éxito te seguirá.",
    "La constancia vence al talento.",
    "Cree en ti, tú puedes con todo.",
    "Sonríe, la vida es bella.",
    "Todo esfuerzo tiene su recompensa.",
    "Rodéate de quienes te hagan sentir en casa.",
    "Un pequeño paso hoy es un gran avance mañana.",
    "La felicidad también se construye con detalles.",
    "Agradece lo que tienes y sigue creciendo.",
    "El éxito es la suma de pequeños esfuerzos diarios.",
    "No cuentes los días, haz que los días cuenten.",
    "La única forma de hacer un gran trabajo es amar lo que haces.",
    "Cree que puedes y ya estás a medio camino.",
    "El futuro pertenece a quienes creen en sus sueños.",
    "No te detengas cuando estés cansado, detente cuando hayas terminado.",
    "Cada logro empieza con la decisión de intentarlo.",
    "La disciplina es el puente entre metas y logros.",
    "Haz de cada día tu obra maestra.",
    "Lo que no te desafía, no te cambia.",
    "El optimismo es la fe que lleva al logro.",
    "Nunca subestimes el poder de un nuevo comienzo.",
    "La perseverancia es fallar 19 veces y triunfar la vigésima.",
    "Tu única limitación es la que te pones a ti mismo.",
    "Los grandes logros requieren tiempo y paciencia.",
    "Hoy es el día perfecto para empezar a brillar.",
    "El trabajo duro supera al talento cuando el talento no trabaja duro.",
    "Sé el cambio que quieres ver en el mundo.",
    "La vida es 10% lo que te pasa y 90% cómo reaccionas.",
    "No esperes el momento perfecto, toma el momento y hazlo perfecto.",
    "Cada caída es una lección disfrazada de oportunidad.",
    "La pasión es energía. Enfócate en lo que te emociona.",
    "El éxito no es final, el fracaso no es fatal: el coraje de continuar es lo que cuenta.",
    "Hazlo con el corazón o no lo hagas.",
    "Las oportunidades no ocurren, las creas.",
    "Nunca dejes que el miedo decida tu futuro.",
    "La mejor manera de predecir el futuro es crearlo.",
    "Pequeños progresos diarios llevan a grandes resultados.",
    "Tu potencial es ilimitado, solo tienes que creerlo.",
    "El esfuerzo de hoy es el éxito de mañana.",
    "Sonríe más, preocúpate menos.",
    "La vida recompensa a quienes se atreven a soñar en grande.",
    "No busques la felicidad, créala.",
    "Cada día trae nuevas fuerzas y nuevos pensamientos.",
    "La gratitud convierte lo que tienes en suficiente.",
    "Sé valiente, sé fuerte, sé tú mismo.",
    "Los límites solo existen en tu mente.",
    "Empieza donde estás, usa lo que tienes, haz lo que puedas.",
    "La motivación te pone en marcha, el hábito te mantiene en movimiento.",
    "No mires atrás, no vas en esa dirección.",
    "El único fracaso real es no intentarlo.",
    "Tu actitud puede convertir un día ordinario en extraordinario.",
    "Cree en el proceso, confía en el viaje.",
    "Las estrellas no brillan sin oscuridad.",
    "Hoy decide ser mejor que ayer.",
    "La excelencia no es un acto, es un hábito.",
    "Nunca es demasiado tarde para un nuevo comienzo.",
    "El éxito es caer siete veces y levantarse ocho.",
    "Hazlo ahora. A veces 'después' se convierte en 'nunca'.",
    "La energía positiva atrae resultados positivos.",
    "Tu historia no ha terminado, solo estás en un capítulo.",
    "Sé el motivo por el que alguien sonríe hoy.",
    "La determinación de hoy es el éxito de mañana.",
    "No hay atajos para ningún lugar que valga la pena.",
    "La paciencia y la perseverancia tienen un efecto mágico.",
    "Enfócate en el progreso, no en la perfección.",
    "La vida es demasiado corta para no perseguir tus sueños.",
    "Sé amable contigo mismo, estás haciendo lo mejor que puedes.",
    "El cambio comienza al final de tu zona de confort.",
    "Tu mente es un jardín, cultiva pensamientos positivos.",
    "La felicidad no es algo listo, viene de tus propias acciones.",
    "Haz de la excelencia tu hábito diario.",
    "Los desafíos son lo que hacen la vida interesante.",
    "Cree en ti mismo incluso cuando nadie más lo haga.",
    "El mejor momento para empezar fue ayer. El segundo mejor es ahora.",
    "La consistencia es más importante que la intensidad.",
    "Cada día es un lienzo en blanco, pinta algo hermoso.",
    "No dejes que el ayer ocupe demasiado del hoy.",
    "La fuerza no viene de ganar. Tus luchas desarrollan tus fortalezas.",
    "Sé el héroe de tu propia historia.",
    "El éxito llega para quienes se atreven a empezar.",
    "Agradece el hoy, confía en el mañana.",
    "Tu viaje de mil millas comienza con un solo paso.",
    "La actitud es una pequeña cosa que marca una gran diferencia.",
    "Nunca dejes de aprender, porque la vida nunca deja de enseñar.",
    "La vida es un regalo, ábrelo cada día con entusiasmo.",
    "Sé paciente, las grandes cosas toman tiempo.",
    "El fracaso es simplemente la oportunidad de empezar de nuevo con más inteligencia.",
    "Mantén la cabeza en alto y el corazón más alto aún.",
    "Cada mañana es una nueva oportunidad para reinventarte.",
    "La pasión mueve montañas.",
    "Sé la razón por la que alguien cree en la bondad de las personas.",
    "No compares tu capítulo 1 con el capítulo 20 de alguien más.",
    "El esfuerzo constante produce resultados extraordinarios.",
    "Hoy es el mañana por el que te preocupabas ayer.",
    "La vida comienza al final de tu zona de confort.",
    "Sé valiente lo suficiente para empezar, fuerte lo suficiente para terminar.",
    "Los sueños no funcionan a menos que tú lo hagas.",
    "Cada día es un nuevo comienzo, tómala con ambas manos.",
    "La positividad es una superpotencia.",
    "Nunca subestimes el impacto de un acto de bondad.",
    "Tu futuro se crea por lo que haces hoy, no mañana.",
    "La resiliencia es la clave del éxito a largo plazo.",
    "Haz que cada día cuente.",
    "La mejor inversión que puedes hacer es en ti mismo.",
    "Cree, actúa y logra.",
    "El optimismo es una estrategia para hacer una vida mejor.",
    "Nunca es demasiado tarde para ser lo que podrías haber sido.",
    "La dedicación y el trabajo duro siempre dan frutos.",
    "Sé agradecido por lo que tienes mientras trabajas por lo que quieres.",
    "Cada desafío superado te hace más fuerte.",
    "La vida es un viaje, disfruta del recorrido.",
    "Tu potencial es mayor de lo que imaginas.",
    "El éxito es un viaje, no un destino.",
    "Mantén la fe, lo mejor está por venir.",
    "Sé audaz, sé valiente, sé tú.",
    # Nuevas frases normales
    "El coraje no es la ausencia de miedo, es actuar a pesar de él.",
    "Cada error es un maestro disfrazado.",
    "La disciplina diaria construye el éxito silencioso.",
    "No esperes a sentirte motivado, actúa y la motivación llegará.",
    "Tu mayor competidor eres tú mismo de ayer.",
    "Los pequeños hábitos crean grandes transformaciones.",
    "La gratitud abre puertas que el esfuerzo solo no puede abrir.",
    "Sé constante, no perfecto.",
    "El progreso real ocurre fuera de la zona de confort.",
    "Hoy puedes escribir una página distinta de tu historia.",
    "La perseverancia transforma lo imposible en inevitable.",
    "No te compares, céntrate en tu propia carrera.",
    "Cada día es una segunda oportunidad que no debes desperdiciar.",
    "La pasión sin acción es solo un sueño.",
    "El trabajo en silencio hace el ruido del éxito.",
    "Sé el arquitecto de tu propio destino.",
    "La fuerza interior se forja en las adversidades.",
    "No dejes que el miedo robe tus mejores días.",
    "La excelencia nace de la repetición consciente.",
    "Cada amanecer trae una nueva chance de mejorar.",
    "La actitud positiva es contagiosa, propágala.",
    "El éxito favorece a los que se preparan y actúan.",
    "No hay victoria sin esfuerzo previo.",
    "Tu mente puede ser tu mejor aliada o tu peor enemiga.",
    "Haz de la perseverancia tu mejor hábito.",
    "Los grandes cambios empiezan con pequeñas decisiones.",
    "La vida recompensa a los valientes, no a los perfectos.",
    "Sé paciente contigo mismo mientras creces.",
    "El camino al éxito está pavimentado de constancia.",
    "No busques atajos, construye caminos sólidos.",
    "Cada paso firme te acerca a tu meta.",
    "La resiliencia es el músculo que se fortalece con el uso.",
    "Hoy es el día para demostrar de lo que eres capaz.",
    "La motivación se enciende con acción, no con espera.",
    "Sé agradecido, ambicioso y disciplinado.",
    "El futuro se construye con las decisiones de hoy.",
    "No te rindas cuando estés cerca del objetivo.",
    "La confianza se gana haciendo lo que dices que harás.",
    "Cada desafío es una invitación a crecer.",
    "La energía que pones es la energía que recibes.",
    "Sé el ejemplo que quieres ver en los demás.",
    "El éxito no llega de golpe, llega de golpe en golpe.",
    "Mantén el foco y el resto se acomodará.",
    "La disciplina te libera a largo plazo.",
    "No esperes el momento ideal, créalo.",
    "Cada día bien vivido es un logro.",
    "La pasión te impulsa, la disciplina te sostiene.",
    "Sé más fuerte que tus excusas.",
    "El progreso diario es la mejor métrica de éxito.",
    "No dejes para mañana lo que puedes empezar hoy.",
    "La vida es generosa con quienes dan el primer paso.",
    "Tu determinación define tu destino.",
    "Sé curioso, sé valiente, sé constante.",
    "El fracaso es temporal, rendirse es permanente.",
    "Cada esfuerzo cuenta, aunque no se vea de inmediato.",
    "La mente positiva atrae oportunidades positivas.",
    "Haz de tu rutina un ritual de crecimiento.",
    "No mires el reloj, mira el camino.",
    "La consistencia vence a la inspiración.",
    "Sé el protagonista de tu propia película.",
    "El éxito es la suma de intentos no abandonados.",
    "Cada mañana es un regalo, úsalo sabiamente.",
    "La paciencia es el arte de confiar en el proceso.",
    "No te detengas por las dudas, avanza con ellas.",
    "La gratitud multiplica lo que tienes.",
    "Sé humilde en el éxito y fuerte en la dificultad.",
    "El camino largo bien recorrido vale más que el atajo.",
    "Tu actitud de hoy define tu realidad de mañana.",
    "La disciplina es el amor propio en acción.",
    "No esperes resultados diferentes haciendo siempre lo mismo.",
    "Cada pequeño logro merece ser celebrado.",
    "La vida premia a quienes se muestran constantes.",
    "Sé flexible en el método, firme en el objetivo.",
    "El coraje de empezar es más importante que el miedo a fallar.",
    "Haz de la mejora continua tu estilo de vida.",
    "No compares tu interior con el exterior de otros.",
    "La energía sigue a la atención: elige bien dónde la pones.",
    "Sé agradecido por el camino, no solo por la meta.",
    "El trabajo bien hecho genera orgullo silencioso.",
    "Cada día es una oportunidad de superarte.",
    "La perseverancia convierte lo ordinario en extraordinario.",
    "No dejes que las distracciones roben tu foco.",
    "La confianza se construye con hechos, no con palabras.",
    "Sé paciente, los resultados llegan a su tiempo.",
    "El éxito no es suerte, es preparación encontrando oportunidad.",
    "Haz de la honestidad contigo mismo tu mejor herramienta.",
    "Cada desafío superado suma a tu carácter.",
    "La motivación te inicia, el hábito te completa.",
    "No te rindas en el valle, la cima está cerca.",
    "Sé el cambio que necesitas ver en tu vida.",
    "El progreso real es invisible al principio.",
    "La disciplina te lleva más lejos que la inspiración.",
    "Cada decisión cuenta, elige con intención.",
    "La vida es demasiado valiosa para vivirla a medias.",
    "Sé valiente al soñar y disciplinado al actuar.",
    "El esfuerzo de hoy es el legado de mañana.",
    "No esperes a que las cosas pasen, hazlas pasar.",
    "La gratitud transforma lo ordinario en extraordinario.",
    "Sé constante aunque el progreso sea lento.",
    "El éxito es el resultado de no abandonar.",
    "Cada día es una página en blanco, escribe con propósito.",
    "La resiliencia es la capacidad de levantarse una vez más.",
    "No dejes que el pasado defina tu futuro.",
    "La pasión más la persistencia igualan al éxito.",
    "Sé el dueño de tu tiempo y de tu atención.",
    "El camino al dominio está lleno de práctica diaria.",
    "Haz de la excelencia un hábito, no una excepción.",
    "Cada momento de duda es una oportunidad de reafirmarte.",
    "La actitud correcta convierte obstáculos en escalones.",
    "Sé generoso con tu esfuerzo y paciente con los resultados.",
    "El verdadero progreso se mide en constancia, no en velocidad.",
    "No te detengas por el cansancio, detente por la satisfacción del deber cumplido.",
    "La vida premia a quienes se atreven a intentarlo de nuevo.",
    "Sé claro en tus metas y flexible en tus métodos.",
    "El éxito silencioso es el más duradero.",
    "Cada día bien aprovechado es una victoria.",
    "La disciplina es el puente entre la intención y el logro.",
    "No dejes que el miedo a fallar te impida empezar.",
    "La confianza se construye haciendo lo difícil de forma repetida.",
    "Sé agradecido por lo que tienes y ambicioso por lo que puedes lograr.",
    "El progreso diario es más poderoso que la motivación ocasional.",
    "Haz de tu vida una prueba de que el esfuerzo vale la pena.",
    "Cada caída te enseña cómo levantarte mejor.",
    "La perseverancia es el secreto de todos los grandes logros.",
    "No compares tu ritmo con el de nadie más.",
    "La mente enfocada es imparable.",
    "Sé el ejemplo de lo que es posible con constancia.",
    "El éxito llega a quienes se preparan mientras otros descansan.",
    "Cada día es una oportunidad de demostrar tu valor.",
    "La gratitud y la disciplina son las mejores compañeras del éxito.",
    "No esperes el momento perfecto, el momento se hace perfecto al actuar.",
    "La fuerza se desarrolla enfrentando lo que temes.",
    "Sé paciente con el proceso y exigente contigo mismo.",
    "El trabajo diario construye el destino que deseas.",
    "Cada pequeño avance es una semilla de algo grande.",
    "La actitud positiva no niega los problemas, los supera.",
    "No dejes que las opiniones ajenas definan tu camino.",
    "La excelencia es el resultado de mil pequeños síes diarios.",
    "Sé valiente al empezar y sabio al continuar.",
    "El éxito no es un accidente, es una decisión diaria.",
    "Cada día es una nueva chance de ser mejor que ayer.",
    "La disciplina te da la libertad de lograr lo que quieres.",
    "No te rindas cuando estés cansado, ríndete cuando hayas terminado.",
    "La pasión te da alas, la constancia te da dirección.",
    "Sé el creador de oportunidades, no solo el esperador de ellas.",
    "El progreso real ocurre cuando nadie está mirando.",
    "Cada esfuerzo sincero deja una huella.",
    "La vida es generosa con quienes se muestran constantes.",
    "No dejes que el miedo al juicio te robe tu potencial.",
    "La resiliencia convierte las heridas en sabiduría.",
    "Sé claro en lo que quieres y disciplinado en cómo lo buscas.",
    "El éxito es la consecuencia natural de no abandonar.",
    "Cada mañana es una invitación a crecer un poco más.",
    "La gratitud multiplica, la queja divide.",
    "No compares tu interior con el escaparate de otros.",
    "La disciplina es el lenguaje del amor propio.",
    "Sé paciente, los resultados reales toman su tiempo.",
    "El camino al éxito está hecho de decisiones pequeñas y consistentes.",
    "Cada día bien vivido es un ladrillo en tu futuro.",
    "La motivación se encuentra en el hacer, no en el esperar.",
    "No dejes que las distracciones roben tu energía.",
    "La confianza se gana cumpliendo lo que te prometes a ti mismo.",
    "Sé el arquitecto de tu propia transformación.",
    "El éxito favorece a los preparados que actúan.",
    "Cada desafío es una oportunidad disfrazada.",
    "La perseverancia es más poderosa que el talento sin uso.",
    "No esperes a sentirte listo, empieza y te irás listando.",
    "La actitud correcta hace que el camino sea más llevadero.",
    "Sé agradecido por el proceso, no solo por el resultado.",
    "El trabajo silencioso produce el ruido del éxito.",
    "Cada paso firme cuenta, aunque parezca pequeño.",
    "La disciplina diaria es la mejor inversión en ti mismo.",
    "No dejes que el pasado te robe el presente.",
    "La fuerza interior se construye con cada decisión difícil.",
    "Sé valiente al soñar y metódico al ejecutar.",
    "El éxito es el resultado de muchas pequeñas victorias diarias.",
    "Cada día es una nueva página, escribe con intención.",
    "La gratitud convierte lo suficiente en abundancia.",
    "No te compares, céntrate en tu propia evolución.",
    "La consistencia es el secreto de todos los grandes resultados.",
    "Sé el dueño de tus hábitos y serás el dueño de tu destino.",
    "El progreso real es lento, pero imparable cuando es constante.",
    "Cada esfuerzo cuenta, aunque nadie lo vea.",
    "La paciencia y la acción juntas hacen milagros.",
    "No dejes que el miedo a empezar te detenga.",
    "La disciplina te lleva donde la motivación no alcanza.",
    "Sé claro, sé constante, sé paciente.",
    "El éxito no es un destino, es una forma de viajar.",
    "Cada mañana es una nueva oportunidad de empezar mejor.",
    "La resiliencia es el arte de seguir adelante de todas formas.",
    "No esperes resultados diferentes haciendo siempre lo mismo.",
    "La pasión te inicia, la disciplina te completa.",
    "Sé el ejemplo de lo que es posible con esfuerzo diario.",
    "El trabajo bien hecho genera una satisfacción que nadie puede quitarte.",
    "Cada día es una chance de demostrar de lo que eres capaz.",
    "La gratitud y el esfuerzo son la mejor combinación.",
    "No dejes que las excusas se conviertan en tu hábito.",
    "La confianza se construye con acciones repetidas.",
    "Sé paciente contigo mismo mientras construyes algo grande.",
    "El éxito llega a quienes se muestran constantes en el tiempo.",
    "Cada pequeño paso te acerca más de lo que imaginas.",
    "La actitud positiva transforma el día ordinario en especial.",
    "No compares tu capítulo actual con el final de alguien más.",
    "La disciplina es el puente entre lo que quieres y lo que logras.",
    "Sé valiente al empezar y fuerte al continuar.",
    "El progreso diario es la mejor forma de medirte.",
    "Cada esfuerzo sincero deja una marca positiva.",
    "La vida premia a quienes se atreven a intentarlo una vez más.",
    "No dejes que el cansancio te haga olvidar tu propósito.",
    "La perseverancia convierte lo difícil en habitual.",
    "Sé agradecido por lo que tienes y trabajador por lo que quieres.",
    "El éxito es la suma de intentos no abandonados.",
    "Cada día es una nueva oportunidad de ser mejor.",
    "La mente enfocada logra lo que la mente dispersa solo desea.",
    "No esperes el momento ideal, actúa y lo harás ideal.",
    "La disciplina diaria construye el carácter y el destino.",
    "Sé el creador de tu propia suerte a través del esfuerzo.",
    "El camino al éxito está lleno de constancia, no de atajos.",
    "Cada decisión correcta te acerca a la vida que deseas.",
    "La resiliencia es la capacidad de reinventarte después de cada caída.",
    "No dejes que el miedo al fracaso te robe el éxito posible.",
    "La pasión sin disciplina es solo emoción pasajera.",
    "Sé claro en tus metas y disciplinado en tus acciones diarias.",
    "El éxito real se construye en silencio y se celebra con humildad.",
    "Cada mañana es un regalo, ábrelo con propósito.",
    "La gratitud transforma la perspectiva y multiplica las oportunidades.",
    "No compares tu ritmo, céntrate en tu propia carrera.",
    "La consistencia es más poderosa que la intensidad esporádica.",
    "Sé el dueño de tu atención y de tu energía.",
    "El progreso real ocurre cuando decides no rendirte.",
    "Cada esfuerzo cuenta, aunque el resultado tarde en llegar.",
    "La paciencia es una forma de inteligencia emocional.",
    "No dejes que las distracciones se conviertan en tu rutina.",
    "La disciplina te da la libertad de vivir como realmente quieres.",
    "Sé valiente al soñar en grande y metódico al ejecutar en pequeño.",
    "El éxito es el resultado de muchas decisiones correctas repetidas.",
    "Cada día es una chance de escribir una mejor versión de ti.",
    "La actitud correcta hace que el esfuerzo valga la pena.",
    "No esperes a que las cosas mejoren, mejóralas tú.",
    "La perseverancia es el ingrediente secreto de todos los logros duraderos.",
    "Sé agradecido por el camino y ambicioso por el destino.",
    "El trabajo diario bien hecho construye un futuro sólido.",
    "Cada pequeño avance es una victoria merecida.",
    "La confianza se gana haciendo lo que dices que harás, una y otra vez.",
    "No dejes que el pasado defina lo que eres capaz de hacer hoy.",
    "La disciplina es el amor propio puesto en práctica todos los días.",
    "Sé el ejemplo de lo que es posible con constancia y esfuerzo.",
    "El éxito no llega de golpe, llega de decisión en decisión.",
    "Cada día es una nueva oportunidad de demostrar tu valor.",
    "La gratitud y la acción son la mejor receta para una vida plena.",
    "No compares tu interior con el exterior de los demás.",
    "La consistencia vence a la motivación a largo plazo.",
    "Sé paciente con los resultados y exigente con el proceso.",
    "El progreso real es lento, pero cada paso cuenta.",
    "Cada esfuerzo sincero suma, aunque no se vea de inmediato.",
    "La resiliencia convierte las dificultades en fortalezas.",
    "No dejes que el miedo a no ser perfecto te impida empezar.",
    "La pasión te da el impulso, la disciplina te da la dirección.",
    "Sé claro, sé constante y confía en el proceso.",
    "El éxito es la consecuencia natural de no abandonar nunca.",
    "Cada mañana es una invitación a crecer un poco más.",
    "La actitud positiva no elimina los problemas, los hace más manejables.",
    "No esperes el momento perfecto, el momento se perfecciona al actuar.",
    "La disciplina diaria es la mejor forma de respetarte a ti mismo.",
    "Sé el arquitecto de tu propio destino a través de tus hábitos.",
    "El trabajo silencioso produce los mejores resultados.",
    "Cada paso firme te acerca más a la meta, aunque parezca lejano.",
    "La gratitud multiplica lo bueno y disminuye lo difícil.",
    "No dejes que las opiniones ajenas dirijan tu camino.",
    "La consistencia es el secreto de quienes logran grandes cosas.",
    "Sé valiente al empezar y sabio al persistir.",
    "El éxito llega a quienes se preparan mientras otros esperan.",
    "Cada día es una chance de ser un poco mejor que ayer.",
    "La disciplina es el puente entre la intención y el logro real.",
    "No compares tu ritmo con el de nadie, corre tu propia carrera.",
    "La perseverancia transforma lo imposible en posible.",
    "Sé agradecido por lo que tienes mientras construyes lo que quieres.",
    "El progreso diario es la mejor métrica de una vida bien vivida.",
    "Cada esfuerzo cuenta, cada decisión importa.",
    "La resiliencia es la capacidad de seguir adelante de todas formas.",
    "No dejes que el cansancio te haga olvidar por qué empezaste.",
    "La pasión más la constancia igualan a resultados extraordinarios.",
    "Sé el dueño de tus hábitos y serás el dueño de tu vida.",
    "El éxito real se construye día a día, no de golpe.",
    "Cada mañana es un regalo, úsalo con intención.",
    "La gratitud transforma la perspectiva y abre puertas.",
    "No esperes a sentirte motivado, actúa y la motivación te seguirá.",
    "La disciplina te lleva más lejos que cualquier chispa de inspiración.",
    "Sé claro en lo que quieres y disciplinado en cómo lo buscas.",
    "El trabajo bien hecho genera una satisfacción profunda.",
    "Cada pequeño avance es una semilla de algo grande.",
    "La actitud correcta convierte los obstáculos en oportunidades.",
    "No dejes que el miedo al juicio te robe tu potencial.",
    "La consistencia es más importante que la intensidad ocasional.",
    "Sé paciente con el proceso y generoso con tu esfuerzo.",
    "El éxito es el resultado de muchas pequeñas victorias diarias.",
    "Cada día es una nueva página, escribe con propósito.",
    "La resiliencia convierte las caídas en lecciones valiosas.",
    "No compares tu capítulo 1 con el capítulo 20 de alguien más.",
    "La disciplina es el lenguaje del respeto hacia ti mismo.",
    "Sé valiente al soñar y metódico al ejecutar.",
    "El progreso real ocurre cuando decides no rendirte nunca.",
    "Cada esfuerzo sincero deja una huella positiva.",
    "La gratitud y la acción son la mejor combinación para crecer.",
    "No dejes que las distracciones se conviertan en tu costumbre.",
    "La pasión te inicia, la disciplina te sostiene hasta el final.",
    "Sé el ejemplo de lo que es posible con esfuerzo constante.",
    "El éxito no es un accidente, es el resultado de decisiones diarias.",
    "Cada mañana es una oportunidad de empezar mejor que ayer.",
    "La actitud positiva hace que el camino sea más llevadero.",
    "No esperes el momento ideal, créalo con tus acciones.",
    "La disciplina diaria construye el futuro que deseas.",
    "Sé agradecido por el camino y ambicioso por el destino.",
    "El trabajo silencioso produce el ruido del éxito verdadero.",
    "Cada paso firme cuenta, aunque parezca insignificante.",
    "La resiliencia es el músculo que se fortalece con cada dificultad.",
    "No dejes que el pasado te limite el presente.",
    "La consistencia vence a la inspiración a largo plazo.",
    "Sé claro, sé constante y confía en tu proceso.",
    "El éxito llega a quienes se muestran firmes en el tiempo.",
    "Cada día es una chance de demostrar de lo que eres capaz.",
    "La gratitud multiplica lo que tienes y abre nuevas puertas.",
    "No compares tu ritmo, céntrate en tu propia evolución.",
    "La disciplina es el puente entre lo que quieres y lo que logras.",
    "Sé valiente al empezar y fuerte al continuar hasta el final.",
    "El progreso diario es la mejor forma de medirte a ti mismo.",
    "Cada esfuerzo cuenta, aunque el resultado tarde en llegar.",
    "La perseverancia es el secreto de todos los grandes logros.",
    "No dejes que el miedo a fallar te impida intentar.",
    "La pasión más la persistencia producen resultados extraordinarios.",
    "Sé el arquitecto de tu propio destino a través de tus hábitos diarios.",
    "El éxito real se construye en silencio y se celebra con humildad.",
    "Cada mañana es un regalo, ábrelo con propósito y gratitud.",
    "La actitud correcta transforma los desafíos en oportunidades de crecimiento.",
    "No esperes a que las cosas pasen, hazlas pasar con tu esfuerzo.",
    "La disciplina te da la libertad de vivir la vida que realmente quieres.",
    "Sé paciente con los resultados y exigente con el proceso diario.",
    "El trabajo bien hecho genera una satisfacción que nadie puede quitarte.",
    "Cada pequeño avance es una victoria que merece ser reconocida.",
    "La resiliencia convierte las heridas en sabiduría y fuerza.",
    "No dejes que las opiniones ajenas definan tu valor o tu camino.",
    "La consistencia es el secreto de quienes logran cosas grandes y duraderas.",
    "Sé agradecido por lo que tienes mientras trabajas por lo que quieres lograr.",
    "El éxito es la suma de muchas decisiones correctas tomadas de forma consistente.",
    "Cada día es una nueva oportunidad de ser un poco mejor que ayer.",
    "La gratitud transforma la perspectiva y multiplica las oportunidades.",
    "No compares tu interior con el escaparate de los demás.",
    "La disciplina diaria es la mejor inversión que puedes hacer en ti mismo.",
    "Sé valiente al soñar en grande y disciplinado al actuar en pequeño.",
    "El progreso real es lento, pero imparable cuando es constante.",
    "Cada esfuerzo sincero suma, aunque no se vea de inmediato.",
    "La perseverancia transforma lo difícil en habitual y lo imposible en posible.",
    "No dejes que el cansancio te haga olvidar tu propósito original.",
    "La pasión te da el impulso inicial, la disciplina te lleva hasta el final.",
    "Sé el dueño de tus hábitos y serás el dueño de tu destino.",
    "El éxito no llega de golpe, llega de decisión en decisión, día tras día.",
    "Cada mañana es una invitación a crecer un poco más y a empezar mejor.",
    "La actitud positiva no niega los problemas, los enfrenta con mejor energía.",
    "No esperes el momento perfecto, el momento se hace perfecto cuando actúas.",
    "La disciplina es el lenguaje del amor propio puesto en práctica todos los días.",
    "Sé claro en tus metas y flexible en los métodos para alcanzarlas.",
    "El trabajo silencioso produce los resultados más sólidos y duraderos.",
    "Cada paso firme te acerca más a la meta, aunque el camino parezca largo.",
    "La resiliencia es la capacidad de levantarse una vez más de lo que caes.",
    "No dejes que el miedo al juicio te robe la oportunidad de brillar.",
    "La consistencia es más poderosa que cualquier chispa de motivación pasajera.",
    "Sé paciente con el proceso y generoso con tu esfuerzo diario.",
    "El éxito es el resultado de muchas pequeñas victorias acumuladas en el tiempo.",
    "Cada día es una página en blanco, escribe con intención y propósito.",
    "La gratitud convierte lo ordinario en extraordinario y lo suficiente en abundancia.",
    "No compares tu ritmo con el de nadie más, corre tu propia carrera.",
    "La disciplina te lleva donde la inspiración sola no puede llegar.",
    "Sé el ejemplo de lo que es posible cuando se combina esfuerzo y constancia.",
    "El progreso real ocurre cuando decides no rendirte, pase lo que pase.",
    "Cada esfuerzo cuenta, cada decisión importa, cada día suma.",
    "La perseverancia es el ingrediente secreto de todos los logros que valen la pena.",
    "No dejes que las distracciones se conviertan en tu nueva rutina.",
    "La pasión te inicia el camino, la disciplina te mantiene en él hasta el final.",
    "Sé agradecido por el camino recorrido y ambicioso por el que aún queda por recorrer.",
    "El éxito real se construye día a día, con acciones pequeñas pero consistentes.",
    "Cada mañana es un regalo, úsalo con propósito, gratitud y determinación.",
    "La actitud correcta hace que incluso los días difíciles se sientan más llevaderos.",
    "No esperes a sentirte listo, empieza y te irás preparando en el camino.",
    "La disciplina diaria construye el carácter, la confianza y el destino que deseas.",
    "Sé valiente al empezar, sabio al continuar y fuerte al terminar lo que iniciaste.",
    "El trabajo bien hecho genera un orgullo silencioso que nadie puede quitarte.",
    "Cada pequeño avance es una semilla que, con el tiempo, se convierte en algo grande.",
    "La resiliencia convierte cada dificultad en una lección y cada caída en un impulso.",
    "No dejes que el pasado te robe la energía del presente ni la esperanza del futuro.",
    "La consistencia es el secreto de quienes logran resultados extraordinarios y duraderos.",
    "Sé claro en lo que quieres, disciplinado en cómo lo buscas y paciente con los tiempos.",
    "El éxito no es un destino final, es una forma de viajar y de vivir cada día.",
    "Cada día es una nueva oportunidad de demostrar de lo que eres realmente capaz.",
    "La gratitud multiplica lo bueno, disminuye lo difícil y abre puertas inesperadas.",
    "No compares tu capítulo actual con el final de la historia de alguien más.",
    "La disciplina es el puente más sólido entre lo que deseas y lo que logras.",
    "Sé el arquitecto de tu propia transformación a través de tus hábitos diarios.",
    "El progreso real es invisible al principio, pero imparable cuando se mantiene constante.",
    "Cada esfuerzo sincero deja una huella positiva, aunque no se vea de inmediato.",
    "La perseverancia transforma lo ordinario en extraordinario y lo difícil en posible.",
    "No dejes que el miedo a no ser perfecto te impida dar el primer paso.",
    "La pasión te da las alas, la disciplina te da la dirección y la constancia te lleva lejos.",
    "Sé el dueño de tu atención, de tu energía y de tus hábitos diarios.",
    "El éxito llega a quienes se preparan en silencio mientras otros esperan la suerte.",
    "Cada mañana es una invitación a reinventarte un poco más y a empezar mejor.",
    "La actitud positiva no elimina los obstáculos, pero te da la fuerza para superarlos.",
    "No esperes el momento ideal, actúa con lo que tienes y harás el momento ideal.",
    "La disciplina diaria es la mejor forma de respetarte a ti mismo y a tus metas.",
    "Sé paciente con los resultados y exigente con el proceso que sigues cada día.",
    "El trabajo silencioso produce el ruido más poderoso: el del éxito verdadero.",
    "Cada paso firme cuenta, aunque parezca pequeño o lento en el momento.",
    "La resiliencia es el arte de seguir adelante incluso cuando todo parece en contra.",
    "No dejes que las opiniones ajenas dirijan tu camino ni definan tu valor.",
    "La consistencia es más importante que la intensidad cuando se trata de logros duraderos.",
    "Sé agradecido por lo que tienes mientras construyes con esfuerzo lo que quieres lograr.",
    "El éxito es la suma de muchas decisiones correctas tomadas de forma consistente en el tiempo.",
    "Cada día es una chance de escribir una mejor versión de ti mismo.",
    "La gratitud transforma la perspectiva, multiplica las oportunidades y suaviza el camino.",
    "No compares tu ritmo ni tu proceso con el de nadie más.",
    "La disciplina te da la libertad de vivir la vida que realmente deseas construir.",
    "Sé valiente al soñar en grande y metódico al ejecutar cada pequeño paso.",
    "El progreso diario es la mejor forma de medirte y de celebrar tu crecimiento.",
    "Cada esfuerzo cuenta, cada decisión importa y cada día suma al resultado final.",
    "La perseverancia es el secreto de todos los grandes logros que resisten el tiempo.",
    "No dejes que el cansancio te haga olvidar por qué empezaste este camino.",
    "La pasión te inicia, la disciplina te sostiene y la constancia te lleva hasta la meta.",
    "Sé el ejemplo de lo que es posible cuando se combina esfuerzo diario con paciencia.",
    "El éxito real se construye en silencio, con acciones consistentes y sin necesidad de aplausos.",
    "Cada mañana es un regalo, ábrelo con propósito, gratitud y la decisión de mejorar.",
    "La actitud correcta convierte los días ordinarios en oportunidades extraordinarias.",
    "No esperes a que las cosas mejoren solas, mejóralas tú con tu esfuerzo diario.",
    "La disciplina es el lenguaje del amor propio y del respeto hacia tus propias metas.",
    "Sé claro en tus objetivos, flexible en los métodos y firme en la constancia.",
    "El trabajo bien hecho genera una satisfacción profunda que nadie puede quitarte.",
    "Cada pequeño avance es una victoria merecida y una semilla de algo aún más grande.",
    "La resiliencia convierte cada caída en una lección y cada dificultad en una fortaleza.",
    "No dejes que el miedo al fracaso te robe la posibilidad de lograr el éxito.",
    "La consistencia es el secreto de quienes construyen resultados que perduran en el tiempo.",
    "Sé paciente con el proceso, generoso con tu esfuerzo y agradecido por cada avance.",
    "El éxito no es un accidente ni una cuestión de suerte, es el resultado de decisiones diarias.",
    "Cada día es una nueva oportunidad de ser mejor, de crecer y de avanzar un poco más.",
    "La gratitud multiplica lo que tienes, abre nuevas puertas y transforma la forma de ver la vida.",
    "No compares tu interior con el exterior de los demás ni tu proceso con el de nadie.",
    "La disciplina diaria construye el carácter, la confianza y el futuro que realmente deseas.",
    "Sé el dueño de tus hábitos, de tu atención y de la energía que dedicas cada día.",
    "El progreso real ocurre cuando decides no rendirte, incluso cuando el camino se pone difícil.",
    "Cada esfuerzo sincero suma, cada decisión correcta cuenta y cada día bien vivido importa.",
    "La perseverancia transforma lo imposible en posible y lo difícil en parte del camino.",
    "No dejes que las distracciones se conviertan en tu nueva normalidad ni en tu excusa.",
    "La pasión te da el impulso, la disciplina te da la dirección y la constancia te lleva lejos.",
    "Sé agradecido por el camino recorrido y ambicioso por el que aún queda por construir.",
    "El éxito real se construye día a día, con acciones pequeñas, consistentes y bien hechas.",
    "Cada mañana es una invitación a crecer, a mejorar y a empezar un poco mejor que ayer.",
    "La actitud positiva no niega los problemas, pero te da la energía para enfrentarlos mejor.",
    "No esperes el momento perfecto, actúa con lo que tienes y harás el momento más perfecto posible.",
    "La disciplina es el puente más confiable entre la intención y el logro real y duradero.",
    "Sé valiente al empezar, sabio al continuar y fuerte al terminar lo que te propones.",
    "El trabajo silencioso produce los resultados más sólidos, duraderos y satisfactorios.",
    "Cada paso firme te acerca a la meta, aunque el camino parezca largo o el progreso lento.",
    "La resiliencia es la capacidad de levantarse una vez más de las veces que caes.",
    "No dejes que el pasado te limite ni que el miedo al futuro te paralice en el presente.",
    "La consistencia es más poderosa que cualquier motivación pasajera o chispa de inspiración.",
    "Sé claro en lo que quieres lograr, disciplinado en cómo lo buscas y paciente con los tiempos.",
    "El éxito es la consecuencia natural de no abandonar nunca, de seguir adelante día tras día.",
    "Cada día es una chance de demostrar de lo que eres capaz y de crecer un poco más.",
    "La gratitud transforma la perspectiva, multiplica las oportunidades y suaviza incluso los días difíciles.",
    "No compares tu ritmo ni tu proceso con el de nadie, céntrate en tu propia evolución.",
    "La disciplina te da la libertad de construir y vivir la vida que realmente deseas.",
    "Sé el ejemplo de lo que es posible cuando se combina esfuerzo diario con paciencia y constancia.",
    "El progreso diario es la mejor forma de medirte, de crecer y de celebrar tu propio avance.",
    "Cada esfuerzo cuenta, cada decisión importa y cada día bien aprovechado suma al resultado final.",
    "La perseverancia es el secreto de todos los grandes logros que resisten el paso del tiempo.",
    "No dejes que el cansancio te haga olvidar por qué empezaste ni hacia dónde quieres llegar.",
    "La pasión te inicia el camino, la disciplina te mantiene en él y la constancia te lleva hasta la meta.",
    "Sé agradecido por lo que tienes mientras construyes con esfuerzo y paciencia lo que quieres lograr.",
    "El éxito real se construye en silencio, con acciones consistentes y sin necesidad de reconocimiento constante.",
    "Cada mañana es un regalo, ábrelo con propósito, gratitud y la firme decisión de mejorar un poco más.",
    # --- Frases sutiles (doble intención: calidad > velocidad) ---
    "La excelencia no tiene atajos.",
    "Hazlo bien… o hazlo dos veces.",
    "La prisa es mala consejera.",
    "Más vale lento y bien que rápido y mal.",
    "La calidad nunca pasa de moda.",
    "Lo que se hace con prisa, se revisa con calma… y se corrige con tiempo.",
    "Velocidad sin precisión es solo ruido.",
    "El buen trabajo se nota… y se recuerda.",
    "No todo lo rápido llega primero.",
    "La paciencia también es una forma de eficiencia.",
    "Mejor una vez bien que mil veces a medias.",
    "La prisa no construye, solo apura.",
    "Lo bien hecho, bien parece.",
    "La calidad se nota cuando nadie está mirando.",
    "No se trata de llegar primero, se trata de llegar bien.",
    "El detalle marca la diferencia.",
    "A veces ir despacio es la forma más rápida de avanzar.",
    "La verdadera eficiencia empieza por hacerlo bien.",
    "Lo urgente no siempre es lo importante.",
    "Un trabajo bien hecho ahorra explicaciones.",
    "La prisa es el enemigo silencioso de la calidad.",
    "Hazlo con calma… y que se note.",
    "El tiempo que se invierte en hacerlo bien, nunca se pierde.",
    "La calidad no se improvisa.",
    "Mejor prevenir que corregir… y volver a empezar.",
    "Lo rápido se olvida, lo bien hecho permanece.",
    "No hay gloria en terminar mal solo por terminar pronto.",
    "La velocidad es útil… cuando va acompañada de acierto.",
    "Hacerlo mal y rápido solo multiplica el trabajo.",
    "La calidad es la mejor forma de ahorrar tiempo a largo plazo.",
    "Un error por prisa cuesta más que una pausa por cuidado.",
    "El buen hacer no entiende de relojes.",
    "Más vale un resultado sólido que diez a medias.",
    "La prisa deja rastros… y no siempre buenos.",
    "Hazlo una vez, hazlo bien.",
    "La calidad no negocia con la urgencia.",
    "Ir despacio no es perder tiempo, es invertirlo bien.",
    "Lo que se hace con cuidado, se defiende solo.",
    "La eficiencia real empieza por no tener que repetir.",
    "No todo lo que brilla por su rapidez vale la pena.",
    # Nuevas frases sutiles
    "La prisa construye problemas, la calma construye soluciones.",
    "Un trabajo mediocre se nota más que uno lento pero impecable.",
    "La calidad no pide permiso a la urgencia.",
    "Hacerlo rápido no es lo mismo que hacerlo bien.",
    "El tiempo invertido en precisión siempre se recupera.",
    "La prisa es el atajo que termina siendo el camino más largo.",
    "Lo bien hecho no necesita justificación.",
    "La excelencia se toma su tiempo… y vale la pena.",
    "No hay premio por terminar mal antes que nadie.",
    "La calidad es el mejor filtro contra las prisas innecesarias.",
    "Un detalle descuidado por prisa puede costar más que el trabajo entero.",
    "La calma es la aliada silenciosa de la precisión.",
    "Hacerlo bien la primera vez es la verdadera velocidad.",
    "La prisa no mejora el resultado, solo acelera el error.",
    "La calidad se construye con atención, no con reloj.",
    "Más vale un paso seguro que diez tropiezos rápidos.",
    "Lo urgente pasa, lo bien hecho permanece.",
    "La prisa es el enemigo de la excelencia.",
    "Un trabajo bien pensado ahorra correcciones innecesarias.",
    "La calidad no se mide en minutos, se mide en resultados.",
    "Hacerlo despacio y bien es más rápido que hacerlo mal y repetir.",
    "La prisa deja huellas que la calidad nunca dejaría.",
    "El cuidado en cada detalle es la mejor inversión de tiempo.",
    "No hay atajo que merezca la pena si el resultado es mediocre.",
    "La excelencia prefiere la precisión a la velocidad.",
    "Un error por apuro cuesta más que una pausa por calidad.",
    "La calidad se nota en el resultado, no en el reloj.",
    "La prisa no construye confianza, la precisión sí.",
    "Hacerlo bien es la forma más eficiente de trabajar.",
    "La calma produce resultados que la prisa solo puede envidiar.",
    "Lo bien hecho no necesita ser justificado ni defendido.",
    "La calidad es el mejor argumento contra la urgencia ciega.",
    "Un trabajo sólido no se mide por cuánto tardó, sino por cómo quedó.",
    "La prisa es el camino corto hacia el retrabajo.",
    "La precisión es una forma de respeto hacia el resultado.",
    "Hacerlo una vez bien es más rápido que hacerlo muchas veces mal.",
    "La calidad no se negocia con la prisa del momento.",
    "El tiempo que se dedica a hacerlo bien nunca es tiempo perdido.",
    "La prisa genera ruido, la calidad genera confianza.",
    "Un resultado impecable vale más que mil entregas apresuradas.",
    "La excelencia se construye con paciencia y atención.",
    "No hay gloria en llegar primero si se llega mal.",
    "La calidad es el mejor ahorro de tiempo a largo plazo.",
    "La prisa es mala amiga del buen trabajo.",
    "Hacerlo con cuidado es la forma más inteligente de avanzar.",
    "La precisión convierte el tiempo en inversión, no en gasto.",
    "Lo bien hecho se defiende solo, lo apresurado necesita explicaciones.",
    "La calidad no entiende de relojes, entiende de resultados.",
    "Un error por prisa se paga con tiempo doble o triple.",
    "La calma es la mejor herramienta para la excelencia.",
    "Hacerlo bien la primera vez es la verdadera eficiencia.",
    "La prisa no mejora nada, solo acelera lo que ya estaba mal planteado.",
    "La calidad se nota cuando el trabajo se entrega y no necesita correcciones.",
    "Más vale un resultado sólido que una entrega rápida y frágil.",
    "La prisa construye problemas futuros, la calidad los evita.",
    "El cuidado en el proceso es la mejor garantía del resultado.",
    "No hay atajo que merezca la pena si el resultado no es bueno.",
    "La excelencia prefiere el tiempo bien invertido a la velocidad vacía.",
    "Un trabajo bien hecho ahorra más tiempo del que consume.",
    "La prisa es el enemigo silencioso de la precisión.",
    "La calidad no se improvisa ni se acelera, se construye.",
    "Hacerlo despacio y bien es más rápido que el ciclo de errores.",
    "La calma produce resultados que la prisa solo puede desear.",
    "Lo bien hecho no necesita defensa, se sostiene solo.",
    "La calidad es el mejor filtro contra las urgencias innecesarias.",
    "Un detalle descuidado por prisa puede arruinar el conjunto.",
    "La precisión es una forma de respeto hacia el trabajo y hacia quien lo recibe.",
    "Hacerlo una vez bien es la forma más inteligente de trabajar.",
    "La prisa deja rastros que la calidad nunca dejaría.",
    "El tiempo invertido en hacerlo bien siempre se recupera con creces.",
    "La excelencia no compite con la velocidad, la supera con resultados.",
    "No hay premio por terminar mal antes que el resto.",
    "La calidad se construye con atención plena, no con reloj en mano.",
    "La prisa es el camino más corto hacia el retrabajo y la frustración.",
    "Un resultado impecable vale más que cualquier entrega apresurada.",
    "La calma es la aliada natural de la precisión y la excelencia.",
    "Hacerlo bien es la mejor forma de respetar el tiempo de todos.",
    "La calidad no se mide en minutos, se mide en la solidez del resultado.",
    "La prisa genera más trabajo del que pretende ahorrar.",
    "El cuidado en cada paso es la mejor inversión de tiempo posible.",
    "No hay atajo que valga la pena si el resultado es mediocre o incompleto.",
    "La excelencia se toma el tiempo necesario y siempre vale la pena.",
    "Un error por apuro cuesta más que una pausa consciente por calidad.",
    "La calidad se nota en el resultado final, no en la velocidad de entrega.",
    "La prisa no construye confianza ni reputación, la precisión sí.",
    "Hacerlo bien la primera vez es la verdadera forma de ser eficiente.",
    "La calma produce resultados que la prisa solo puede envidiar en silencio.",
    "Lo bien hecho no necesita ser justificado ni explicado después.",
    "La calidad es el mejor argumento contra cualquier urgencia mal planteada.",
    "Un trabajo sólido no se mide por cuánto tardó, sino por cómo quedó al final.",
    "La prisa es el camino corto hacia el retrabajo y la pérdida de tiempo.",
    "La precisión es una forma de respeto hacia el resultado y hacia quien lo espera.",
    "Hacerlo una vez bien es más rápido y más inteligente que hacerlo muchas veces mal.",
    "La calidad no negocia con la prisa del momento ni con la urgencia ciega.",
    "El tiempo que se dedica a hacerlo bien nunca es tiempo perdido, es tiempo invertido.",
    "La prisa genera ruido y problemas, la calidad genera confianza y solidez.",
    "Un resultado impecable vale más que mil entregas apresuradas y frágiles.",
    "La excelencia se construye con paciencia, atención y respeto por el proceso.",
    "No hay gloria en llegar primero si se llega mal o incompleto.",
    "La calidad es el mejor ahorro de tiempo, de esfuerzo y de explicaciones a largo plazo.",
    "La prisa es mala compañera del buen trabajo y de los buenos resultados.",
    "Hacerlo con cuidado es la forma más inteligente y eficiente de avanzar.",
    "La precisión convierte el tiempo en una inversión, nunca en un gasto.",
    "Lo bien hecho se defiende solo, lo apresurado necesita constantes justificaciones.",
    "La calidad no entiende de relojes ni de urgencias, entiende de resultados sólidos.",
    "Un error por prisa se paga siempre con tiempo doble, triple o más.",
    "La calma es la mejor herramienta para alcanzar la excelencia real.",
    "Hacerlo bien la primera vez es la verdadera definición de eficiencia.",
    "La prisa no mejora nada, solo acelera lo que ya estaba mal planteado desde el inicio.",
    "La calidad se nota cuando el trabajo se entrega y no necesita correcciones posteriores.",
    "Más vale un resultado sólido y bien terminado que una entrega rápida y frágil.",
    "La prisa construye problemas futuros, la calidad los evita desde el principio.",
    "El cuidado en el proceso es la mejor garantía de un resultado que resista el tiempo.",
    "No hay atajo que merezca la pena si el resultado final no es bueno ni completo.",
    "La excelencia prefiere el tiempo bien invertido a cualquier velocidad vacía.",
    "Un trabajo bien hecho ahorra más tiempo del que consume en el proceso.",
    "La prisa es el enemigo silencioso de la precisión y de la calidad real.",
    "La calidad no se improvisa, no se acelera y no se negocia con la urgencia.",
    "Hacerlo despacio y bien es siempre más rápido que el ciclo infinito de errores y correcciones.",
    "La calma produce resultados que la prisa solo puede desear desde lejos.",
    "Lo bien hecho no necesita defensa ni justificación, se sostiene solo con su solidez.",
    "La calidad es el mejor filtro posible contra las urgencias innecesarias y mal planteadas.",
    "Un detalle descuidado por prisa puede arruinar el conjunto entero del trabajo.",
    "La precisión es una forma de respeto hacia el trabajo, hacia el resultado y hacia quien lo recibe.",
    "Hacerlo una vez bien es la forma más inteligente, eficiente y profesional de trabajar.",
    "La prisa deja rastros que la calidad nunca dejaría ni permitiría.",
    "El tiempo invertido en hacerlo bien siempre se recupera con creces en el futuro.",
    "La excelencia no compite con la velocidad, la supera claramente con los resultados.",
    "No hay premio ni reconocimiento por terminar mal antes que el resto.",
    "La calidad se construye con atención plena y respeto por cada detalle, no con reloj en mano.",
    "La prisa es el camino más corto hacia el retrabajo, la frustración y la pérdida de tiempo.",
    "Un resultado impecable vale más que cualquier entrega apresurada, incompleta o frágil.",
    "La calma es la aliada natural de la precisión, de la excelencia y de los buenos resultados.",
    "Hacerlo bien es la mejor forma de respetar el tiempo de todos los involucrados.",
    "La calidad no se mide en minutos ni en velocidad, se mide en la solidez del resultado final.",
    "La prisa genera más trabajo, más problemas y más tiempo perdido del que pretende ahorrar.",
    "El cuidado en cada paso del proceso es la mejor inversión de tiempo posible.",
    "No hay atajo que valga la pena si el resultado es mediocre, incompleto o frágil.",
    "La excelencia se toma el tiempo necesario para hacerse bien y siempre vale la pena.",
    "Un error por apuro cuesta siempre más que una pausa consciente por calidad y precisión.",
    "La calidad se nota en el resultado final, no en la velocidad con la que se entregó.",
    "La prisa no construye confianza ni reputación, la precisión y la calidad sí lo hacen.",
    "Hacerlo bien la primera vez es la verdadera y única forma de ser realmente eficiente.",
    "La calma produce resultados que la prisa solo puede envidiar en silencio y desde lejos.",
    "Lo bien hecho no necesita ser justificado, explicado ni defendido después de entregado.",
    "La calidad es el mejor argumento posible contra cualquier urgencia mal planteada o innecesaria.",
    "Un trabajo sólido no se mide por cuánto tardó en hacerse, sino por cómo quedó al final.",
    "La prisa es el camino corto hacia el retrabajo, la pérdida de tiempo y la frustración.",
    "La precisión es una forma de respeto hacia el resultado, hacia el proceso y hacia quien lo espera.",
    "Hacerlo una vez bien es más rápido, más inteligente y más profesional que hacerlo muchas veces mal.",
    "La calidad no negocia con la prisa del momento ni con la urgencia ciega del día a día.",
    "El tiempo que se dedica a hacerlo bien nunca es tiempo perdido, es siempre tiempo bien invertido.",
    "La prisa genera ruido, problemas y correcciones, la calidad genera confianza y solidez.",
    "Un resultado impecable vale más que mil entregas apresuradas, incompletas o frágiles.",
    "La excelencia se construye con paciencia, atención plena y respeto profundo por el proceso.",
    "No hay gloria ni reconocimiento en llegar primero si se llega mal, incompleto o frágil.",
    "La calidad es el mejor ahorro de tiempo, de esfuerzo y de explicaciones a largo plazo.",
    "La prisa es mala compañera del buen trabajo, de los buenos resultados y de la reputación.",
    "Hacerlo con cuidado es la forma más inteligente, eficiente y profesional de avanzar.",
    "La precisión convierte el tiempo en una inversión real, nunca en un gasto inútil.",
    "Lo bien hecho se defiende solo con su solidez, lo apresurado necesita constantes justificaciones.",
    "La calidad no entiende de relojes ni de urgencias, entiende únicamente de resultados sólidos y duraderos.",
    "Un error por prisa se paga siempre con tiempo doble, triple o incluso más.",
    "La calma es la mejor herramienta disponible para alcanzar la excelencia real y sostenible.",
    "Hacerlo bien la primera vez es la verdadera definición de eficiencia y de profesionalismo.",
    "La prisa no mejora nada de lo que ya estaba mal planteado, solo acelera el error.",
    "La calidad se nota claramente cuando el trabajo se entrega y no necesita correcciones posteriores.",
    "Más vale un resultado sólido y bien terminado que cualquier entrega rápida y frágil.",
    "La prisa construye problemas futuros que la calidad evita desde el primer momento.",
    "El cuidado en el proceso es la mejor garantía posible de un resultado que resista el tiempo.",
    "No hay atajo que merezca la pena si el resultado final no es bueno, completo y sólido.",
    "La excelencia prefiere siempre el tiempo bien invertido a cualquier velocidad vacía o superficial.",
    "Un trabajo bien hecho ahorra más tiempo del que consume durante el proceso de elaboración.",
    "La prisa es el enemigo silencioso de la precisión, de la calidad y de los buenos resultados.",
    "La calidad no se improvisa, no se acelera artificialmente y no se negocia con la urgencia.",
    "Hacerlo despacio y bien es siempre más rápido que el ciclo infinito de errores y correcciones.",
    "La calma produce resultados que la prisa solo puede desear desde lejos y con envidia.",
    "Lo bien hecho no necesita defensa ni justificación, se sostiene solo con su propia solidez.",
    "La calidad es el mejor filtro posible contra las urgencias innecesarias y mal planteadas.",
    "Un detalle descuidado por prisa puede arruinar el conjunto entero del trabajo y del resultado.",
    "La precisión es una forma de respeto hacia el trabajo, hacia el resultado y hacia quien lo recibe.",
    "Hacerlo una vez bien es la forma más inteligente, eficiente y profesional de trabajar siempre.",
    "La prisa deja rastros que la calidad nunca dejaría ni permitiría en un buen trabajo.",
    "El tiempo invertido en hacerlo bien siempre se recupera con creces en el futuro cercano y lejano.",
    "La excelencia no compite con la velocidad, la supera claramente y de forma contundente con los resultados.",
    "No hay premio ni reconocimiento real por terminar mal antes que el resto de las personas.",
    "La calidad se construye con atención plena y respeto por cada detalle, nunca con reloj en mano.",
    "La prisa es el camino más corto hacia el retrabajo, la frustración y la pérdida innecesaria de tiempo.",
    "Un resultado impecable vale más que cualquier entrega apresurada, incompleta o frágil que se haga.",
    "La calma es la aliada natural de la precisión, de la excelencia y de todos los buenos resultados.",
    "Hacerlo bien es la mejor forma posible de respetar el tiempo de todos los involucrados en el proceso.",
    "La calidad no se mide en minutos ni en velocidad de entrega, se mide en la solidez del resultado final.",
    "La prisa genera más trabajo, más problemas y más tiempo perdido del que pretende ahorrar en el momento.",
    "El cuidado en cada paso del proceso es la mejor inversión de tiempo posible que se puede hacer.",
    "No hay atajo que valga realmente la pena si el resultado es mediocre, incompleto o frágil.",
    "La excelencia se toma el tiempo necesario para hacerse bien y siempre, sin excepción, vale la pena.",
    "Un error por apuro cuesta siempre más que una pausa consciente por calidad y por precisión.",
    "La calidad se nota en el resultado final, nunca en la velocidad con la que se entregó el trabajo.",
    "La prisa no construye confianza ni reputación, la precisión y la calidad sí lo hacen de forma sólida.",
    "Hacerlo bien la primera vez es la verdadera y única forma de ser realmente eficiente y profesional.",
    "La calma produce resultados que la prisa solo puede envidiar en silencio y desde una gran distancia.",
    "Lo bien hecho no necesita ser justificado, explicado ni defendido después de haber sido entregado.",
    "La calidad es el mejor argumento posible contra cualquier urgencia mal planteada o innecesaria del momento.",
    "Un trabajo sólido no se mide por cuánto tardó en hacerse, sino únicamente por cómo quedó al final.",
    "La prisa es el camino corto hacia el retrabajo, la pérdida de tiempo y la frustración acumulada.",
    "La precisión es una forma de respeto hacia el resultado, hacia el proceso y hacia quien lo espera con confianza.",
    "Hacerlo una vez bien es más rápido, más inteligente y más profesional que hacerlo muchas veces mal.",
    "La calidad no negocia con la prisa del momento ni con la urgencia ciega del día a día laboral.",
    "El tiempo que se dedica a hacerlo bien nunca es tiempo perdido, es siempre tiempo bien invertido y recuperable.",
    "La prisa genera ruido, problemas y correcciones constantes, la calidad genera confianza y solidez duradera.",
    "Un resultado impecable vale más que mil entregas apresuradas, incompletas o frágiles que se puedan hacer.",
    "La excelencia se construye con paciencia, atención plena y respeto profundo por cada parte del proceso.",
    "No hay gloria ni reconocimiento real en llegar primero si se llega mal, incompleto o frágil al final.",
    "La calidad es el mejor ahorro de tiempo, de esfuerzo y de explicaciones a largo plazo que existe.",
    "La prisa es mala compañera del buen trabajo, de los buenos resultados y de la reputación profesional.",
    "Hacerlo con cuidado es la forma más inteligente, eficiente y profesional de avanzar en cualquier tarea.",
    "La precisión convierte el tiempo en una inversión real y valiosa, nunca en un gasto inútil o perdido.",
    "Lo bien hecho se defiende solo con su solidez y calidad, lo apresurado necesita constantes justificaciones.",
    "La calidad no entiende de relojes ni de urgencias, entiende únicamente de resultados sólidos y duraderos en el tiempo.",
]